# all.yml
# This file includes all needed group_vars and maps them to their vault vars
# if these are sensitive. The vault vars are encrypted using ansible-vault.
#
# Source:
# http://docs.ansible.com/ansible/playbooks_best_practices.html#best-practices-for-variables-and-vaults
---

include_vars: vault.yml

# Workaround for Ubuntu 16.04LTS since it doesn't come with Python 2.x
# ansible_python_interpreter: /usr/bin/python3


# Global Environment
ruby_env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /home/{{ system_default_user }}
    GOPATH: /home/{{ system_default_user }}/go
    RBENV_SHELL: bash
    RBENV_ROOT: /home/{{system_default_user}}/.rbenv
    PATH:   /usr/local/go/bin:/home/{{system_default_user}}/.rbenv/shims:/home/{{system_default_user}}/.rbenv/plugins/ruby-build/bin:/home/{{system_default_user}}/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    RAILS_ENV: "{{RAILS_ENV}}"
    GO_ENV: "{{GO_ENV | default ('')}}"

go_env: "{{ruby_env}}"
mount_dir: /mnt/lvm
central_log_dir: "{{mount_dir}}/{{orgtype}}/logs/{{ansible_hostname}}"

# System default user varies. (e.g. local-vagrant.yml)
# Therefore overwritten by group/host specific vars.
system_default_user: 'ubuntu'
system_default_group: 'deploy'
system_default_email: "ops@aptrust.org"

# TODO: Revisit this to see if it's still a necessary conditional.
# This variable is used as a conditional for new deploys, to not
# influence existing, non ansbile managed, machines adversely.
newdeploy: False

deploy_user: 'aptdeploy'
deploy_group: 'deploy'

sshd_allow_users: ["{{system_default_user}}",cd3ef,andrew.diamond,adiamond]
sshd_port: ['1984']

# External Filesystems (EBS, EFS)
use_efs: False
use_ebs: False

# EBS Autoscale
ebs_slack_webhook: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62353037386539663565346531306464353961326361363263313130383564633036643764316630
          6466633739376466363432643037396337656431356638350a353134373337363232666561353930
          36666336313663363032366438663366383430323530653965656336313638393436326232343633
          3761306538336232320a313232633030306634643364303865303532653266653331386464393130
          62663338363437333461393931343262646333366336623639653633386164303263386634383937
          35636566363031663462623937623233373262623735393138663834393532636339326434646239
          36343033316262346536303534363336616138386135626230366532643266396239386230333661
          64613235663163343238
ebs_slack_channel: "#ops"


##
# Ruby Variables
##
ruby_version: 2.3.1

# RBenv
# This is set as a fact in the role.
#rbenv_root: /home/{{system_default_user}}/.rbenv
rbenv:
    env: user
    version: v1.0.0
    ruby_version: 2.3.1
rbenv_owner: "{{system_default_user}}"
rbenv_group: 'deploy'
rbenv_users:
    - "{{system_default_user}}"
    - adiamond
    - cd3ef


goapp_log_path: "/mnt/lvm/{{orgtype}}/logs"

##
# Postfix variables
##
postfix_aliases:
    - { user: root, alias: "{{system_default_email}}" }
    - { user: ubuntu, alias: "{{system_default_email}}" }
    - { user: postmaster, alias: "{{system_default_email}}" }
postfix_AWS_aliases:
    - { user: "@{{ ansible_fqdn }}", alias: ops@aptrust.org }
    - { user: "@{{ ansible_hostname }}", alias: ops@aptrust.org }

postfix_relayhost: email-smtp.us-east-1.amazonaws.com
postfix_relayhost_port: 587
postfix_relaytls: true

# AWS IAM SES sending-only credentials
# (used for system emails)
postfix_sasl_user: "{{ vault_postfix_sasl_user }}"
postfix_sasl_pwd: "{{ vault_postfix_sasl_pwd }}"

# AWS Read-only user
aws_ro_user: "{{ vault_aws_ro_user }}"
aws_ro_pwd: "{{ vault_aws_ro_pwd }}"


# AWS Ubuntu user
aws_access_key_ubuntu: "{{vault_aws_access_key_ubuntu}}"
aws_secret_access_key_ubuntu: "{{vault_aws_secret_access_key_ubuntu}}"

# Fluctus AWS SES sending-only
fluctus_aws_ses_user: "{{ vault_fluctus_aws_ses_user }}"
fluctus_aws_ses_pwd: "{{ vault_fluctus_aws_ses_pwd }}"

##
# User variables
##
cd3ef_pwd: "{{ vault_cd3ef_pwd }}"
cd3ef_sshkey: "{{ vault_cd3ef_sshkey }}"

adiamond_pwd: "{{ vault_adiamond_pwd }}"
adiamond_sshkey: "{{ vault_adiamond_sshkey }}"

kec6en_pwd: "{{ vault_kec6en_pwd }}"
kec6en_sshkey: "{{ vault_kec6en_sshkey }}"

aptdeploy_pwd: "{{ vault_aptdeploy_pwd }}"
aptdeploy_sshkey: "{{ vault_aptdeploy_sshkey }}"
aptdeploy_sshkey_private: "{{ vault_aptdeploy_sshkey_private }}"

###
# SSL Certificates
##
ssl_cert: "{{ vault_ssl_cert }}"
ssl_key: "{{ vault_ssl_key }}"
ssl_cert_path: "{{ vault_ssl_cert_path }}"
ssl_key_path: "{{ vault_ssl_key_path }}"
ssl_interm_cert_path: "{{vault_ssl_interm_cert_path}}"
ssl_interm_cert: "{{vault_ssl_interm_cert}}"
ssl_chain: "{{vault_ssl_chain}}"
ssl_chain_path: "{{vault_ssl_chain_path}}"

# SSL role jdauphant.ss-certs
ssl_certs_common_name: "{{ansible_fqdn}}"

##
# AWS Credentials
##
var_aws_access_key_id: "{% if ansible_bios_version != 'VirtualBox' %}{{ vault_aws_access_prod_key_id }}{% else %}{{ vault_aws_access_dev_key_id }}{% endif %}"
var_aws_secret_access_key: "{% if ansible_bios_version != 'VirtualBox' %}{{ vault_aws_secret_access_prod_key}}{% else %}{{ vault_aws_secret_access_dev_key }}{% endif %}"
# var_aws_access_key: "{{vault_aws_access_key}}"
# var_aws_secret_key: "{{vault_aws_secret_key}}"
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

# AWS CLI Role
aws_cli_user: "{{system_default_user}}"
aws_cli_group: "{{system_default_group}}"

var_fluctus_prod_db_host: "{{ vault_fluctus_prod_db_host}}"
var_fluctus_prod_db_user: "{{ vault_fluctus_prod_db_user}}"
var_fluctus_prod_db_pwd: "{{ vault_fluctus_prod_db_pwd}}"

var_fluctus_dev_db_host: "{{ vault_fluctus_dev_db_host}}"
var_fluctus_dev_db_user: "{{ vault_fluctus_dev_db_user}}"
var_fluctus_dev_db_pwd: "{{ vault_fluctus_dev_db_pwd}}"

# Fedora
fedora_db_user: "{{vault_fedora_user}}"
fedora_db_pwd: "{{vault_fedora_pwd}}"
var_fedora_user: "{{vault_fedora_user}}"
var_fedora_pwd: "{{vault_fedora_pwd}}"
var_fedora_prod_pwd: "{{vault_fedora_prod_pwd}}"
var_fedora_pid_namespace: 'aptrust'

# Logwatch
logwatch_email: "ops@aptrust.org"

# PSDash
var_psdash_usr: "{{vault_psdash_usr}}"
var_psdash_pwd: "{{vault_psdash_pwd}}"
psdash_host_address: "psdash.aptrust.org"

# Nagios
nagios_server: nagios.aptrust.org

# Icinga2
icinga_server: icinga.aptrust.org
icinga2_master_hostname: "{{vault_icinga2_master}}"
icinga2_master_host: apt-ops
icinga2_db_host: "{{vault_icinga2_db_host}}"
icinga2_slack_webhook: "{{vault_icinga2_slack_webhook}}"
icinga2_slack_base_url: "{{vault_icinga2_slack_base_url}}"

# Icinga IDO dB
icinga2_db: "{{vault_icinga2_db}}"
icinga2_db_user: "{{vault_icinga2_db_user}}"
icinga2_db_pass: "{{vault_icinga2_db_pwd}}"

icinga2_web2_db: "{{vault_icinga2_web2_db}}"
icinga2_web2_auth_db: "{{vault_icinga2_web2_auth_db}}"
icinga2_web2_db_user: "{{vault_icinga2_web2_db_user}}"
icinga2_web2_db_pass: "{{vault_icinga2_web2_db_pass}}"

influxdbwriter_host: "{{vault_influxdb_host}}"

# InfluxDB
ops_data_influxdb: /srv/nfs/ops_data/influxdb
influxdb_data_dir: "{{ops_data_influxdb}}/data"

influxdb_host: "{{vault_influxdb_host}}"
influxdb_port: "{{vault_influxdb_port}}"
influxdb_username: "{{vault_influxdb_username}}"
influxdb_password: "{{vault_influxdb_password}}"
influxdb_data_wal_dir: "{{ops_data_influxdb}}/wal"

influxdb_meta_https_enabled: "false"
influxdb_meta_https_certificate: "/etc/ssl/influxdb.pem"
influxdb_meta_https_key: "/etc/ssl/influxdb.pem"
influxdb_admin_https_enabled: "true"
influxdb_admin_https_certificate: "/etc/ssl/influxdb.pem"
influxdb_admin_https_key: "/etc/ssl/influxdb.pem"
influxdb_http_https_enabled: "false"
influxdb_http_https_certificate: "/etc/ssl/influxdb.pem"
influxdb_http_https_key: "/etc/ssl/influxdb.pem"

influxdb_hostname: "{{influxdb_host}}"
influxdb_db: 'icinga2'


#
# Grafana
grafana_admin_password: "{{vault_grafana_admin_password}}"
grafana_psql_owner: "{{vault_grafana_psql_owner}}"
grafana_psql_pwd: "{{vault_grafana_psql_pwd}}"
grafana_auth_github_client_id: "{{vault_grafana_auth_github_client_id}}"
grafana_auth_github_client_secret: "{{vault_grafana_auth_github_client_secret}}"


# Fail2Ban settings
fail2ban_config_ignoreip: "{{ hostvars|fetchlistfromdict(groups.all)|map(attribute='host_eip')|join (' ')}}"
fail2ban_config_destemail: ops@aptrust.org
fail2ban_config_maxretry: 1

# Slack
slack_token: "{{vault_slack_token}}"

# NFS
# Ansible host that is serving NFS
nfs_server_host: apt-ops
nfs_server_hostname: 'apt-ops.aptrust.org'
# Directory where NFS exports are served from on nfs server
nfs_export_dir: '/srv/nfs'
# Mount dir for nfs clients
nfs_mount_dir: '/mnt/nfs'
nfs_directories:
  #  - { path: /mnt/data, source: 127.0.0.1, options: "(rw,sync,no_subtree_check,no_root_squash)" }
   - path: "backups"
     source:
        - "apt-demo-repo2.aptrust.org"
        - "apt-demo-services.aptrust.org"
        - "apt-prod-repo2.aptrust.org"
        - "apt-prod-services.aptrust.org"
        - "dpn-prod2.aptrust.org"
        - "dpn-demo2.aptrust.org"
        - "apt-prod-web.aptrust.org"
   - path: "logs"
     source:
        - "apt-demo-repo2.aptrust.org"
        - "apt-demo-services.aptrust.org"
        - "apt-prod-repo2.aptrust.org"
        - "apt-prod-services.aptrust.org"
        - "dpn-prod2.aptrust.org"
        - "dpn-demo2.aptrust.org"
        - "apt-prod-web.aptrust.org"
     options: '(rw,async)'

# Certbot LetsEncrypt
certbot_create_certs: true
certbot_mail_address: admin@aptrust.org
certbot_renew_certs: true
certbot_standalone: false

#PSQL_backup
pg_backup_dir: "/mnt/nfs/backups/psql_backup/{{ansible_hostname}}/"

# Graylog
graylog_dns: "logs.aptrust.org"
graylog_root_password_sha2: "{{vault_graylog_root_password_sha2}}"
graylog_root_password: "{{vault_graylog_root_password}}"
graylog_web_endpoint_uri: http://127.0.0.1:9000/api
