# all.yml
# This file includes all needed group_vars and maps them to their vault vars.
# The vault vars are encrypted using ansible-vault.
#
# Source:
# http://docs.ansible.com/ansible/playbooks_best_practices.html#best-practices-for-variables-and-vaults
---

##
# System Default User
##
system_default_user: "{% if ansible_bios_version != 'VirtualBox' %}ubuntu{% else %}vagrant{% endif %}"
system_deploy_user: aptdeploy
system_deploy_group: deploy

ansible_become_pass: "{{ vault_aptdeploy_password }}"

## 
# Ruby Variables
## 
ruby_version: 2.1.5

##
# Postfix variables
##
postfix_aliases:
    - { user: root, alias: ops@aptrust.org }
    - { user: ubuntu, alias: ops@aptrust.org }
    - { user: postmaster, alias: ops@aptrust.org }
postfix_AWS_aliases:
    - { user: "@{{ ansible_fqdn}}", alias: ops@aptrust.org }

postfix_relayhost: email-smtp.us-east-1.amazonaws.com
postfix_relayhost_port: 25
postfix_relaytls: true

# AWS IAM SES credentials (not access key):
postfix_sasl_user: "{{ vault_postfix_sasl_user }}"
postfix_sasl_password: "{{ vault_postfix_sasl_password }}"

##
# User variables
##
var_cd3ef_password: "{{ vault_cd3ef_password }}"
var_cd3ef_sshkey: "{{ vault_cd3ef_sshkey }}"

#var_andrewdiamond_password: "{{ vault_andrewdiamond_password }}"
#var_andrewdiamond_sshkey: "{{ vault_andrewdiamond_sshkey }}"

var_aptdeploy_password: "{{ vault_aptdeploy_password }}"
var_aptdeploy_sshkey: "{{ vault_aptdeploy_sshkey }}"
var_aptdeploy_sshkey_private: "{{ vault_aptdeploy_sshkey_private }}"

###
# SSL Certificates
##
var_ssl_cert: "{{ vault_ssl_cert }}"
var_ssl_key: "{{ vault_ssl_key }}"
var_ssl_chain: "{{ vault_ssl_chain }}"
var_ssl_cert_path: "{{ vault_ssl_cert_path }}"
var_ssl_key_path: "{{ vault_ssl_key_path }}"
var_ssl_chain_path: "{{ vault_ssl_chain_path }}"

##
# AWS Credentials
##
var_aws_access_key_id: "{% if ansible_bios_version != 'VirtualBox' %}{{ vault_aws_access_prod_key_id }}{% else %}{{ vault_aws_access_dev_key_id }}{% endif %}"
var_aws_secret_access_key: "{% if ansible_bios_version != 'VirtualBox' %}{{ vault_aws_secret_access_prod_key}}{% else %}{{ vault_aws_secret_access_dev_key }}{% endif %}"

