# all.yml
# This file includes all needed group_vars and maps them to their vault vars
# if these are sensitive. The vault vars are encrypted using ansible-vault.
#
# Source:
# http://docs.ansible.com/ansible/playbooks_best_practices.html#best-practices-for-variables-and-vaults
---


##
# System Default User
##

# This is defined in host vars (e.g. local-vagrant.yml)
system_default_user: ubuntu

include_vars: vault.yml
# This variable is used as a conditional for new deploys, to not
# influence existing, non ansbile managed, machines adversely.
newdeploy: False

system_default_email: "ops@aptrust.org"

system_deploy_user: aptdeploy
system_deploy_group: deploy

sshd_allow_users: ["{{system_default_user}}",cd3ef,andrew.diamond,adiamond]
sshd_port: 1984

##
# Ruby Variables
##
ruby_version: 2.1.5

##
# Postfix variables
##
postfix_aliases:
    - { user: root, alias: ops@aptrust.org }
    - { user: ubuntu, alias: ops@aptrust.org }
    - { user: postmaster, alias: ops@aptrust.org }
postfix_AWS_aliases:
    - { user: "@{{ ansible_fqdn }}", alias: ops@aptrust.org }
    - { user: "@{{ ansible_hostname }}", alias: ops@aptrust.org }

postfix_relayhost: email-smtp.us-east-1.amazonaws.com
postfix_relayhost_port: 25
postfix_relaytls: true

# AWS IAM SES credentials (not access key):
postfix_sasl_user: "{{ vault_postfix_sasl_user }}"
postfix_sasl_pwd: "{{ vault_postfix_sasl_pwd }}"

# AWS read-only user
aws_ro_user: "{{ vault_aws_ro_user }}"
aws_ro_pwd: "{{ vault_aws_ro_pwd }}"

# Fluctus
fluctus_aws_ses_user: "{{ vault_fluctus_aws_ses_user }}"
fluctus_aws_ses_pwd: "{{ vault_fluctus_aws_ses_pwd }}"

##
# User variables
##
cd3ef_pwd: "{{ vault_cd3ef_pwd }}"
cd3ef_sshkey: "{{ vault_cd3ef_sshkey }}"

adiamond_pwd: "{{ vault_adiamond_pwd }}"
adiamond_sshkey: "{{ vault_adiamond_sshkey }}"

aptdeploy_pwd: "{{ vault_aptdeploy_pwd }}"
aptdeploy_sshkey: "{{ vault_aptdeploy_sshkey }}"
aptdeploy_sshkey_private: "{{ vault_aptdeploy_sshkey_private }}"

###
# SSL Certificates
##
ssl_cert: "{{ vault_ssl_cert }}"
ssl_key: "{{ vault_ssl_key }}"
ssl_cert_path: "{{ vault_ssl_cert_path }}"
ssl_key_path: "{{ vault_ssl_key_path }}"
ssl_interm_cert_path: "{{vault_ssl_interm_cert_path}}"
ssl_interm_cert: "{{vault_ssl_interm_cert}}"

##
# AWS Credentials
##
var_aws_access_key_id: "{% if ansible_bios_version != 'VirtualBox' %}{{ vault_aws_access_prod_key_id }}{% else %}{{ vault_aws_access_dev_key_id }}{% endif %}"
var_aws_secret_access_key: "{% if ansible_bios_version != 'VirtualBox' %}{{ vault_aws_secret_access_prod_key}}{% else %}{{ vault_aws_secret_access_dev_key }}{% endif %}"

var_fluctus_prod_db_host: "{{ vault_fluctus_prod_db_host}}"
var_fluctus_prod_db_user: "{{ vault_fluctus_prod_db_user}}"
var_fluctus_prod_db_pwd: "{{ vault_fluctus_prod_db_pwd}}"

var_fluctus_dev_db_host: "{{ vault_fluctus_dev_db_host}}"
var_fluctus_dev_db_user: "{{ vault_fluctus_dev_db_user}}"
var_fluctus_dev_db_pwd: "{{ vault_fluctus_dev_db_pwd}}"

# Fedora
fedora_db_user: "{{vault_fedora_user}}"
fedora_db_pwd: "{{vault_fedora_pwd}}"
var_fedora_user: "{{vault_fedora_user}}"
var_fedora_pwd: "{{vault_fedora_pwd}}"
var_fedora_prod_pwd: "{{vault_fedora_prod_pwd}}"
var_fedora_pid_namespace: 'aptrust'

# Logwatch
logwatch_email: "ops@aptrust.org"

# PSDash
var_psdash_usr: "{{vault_psdash_usr}}"
var_psdash_pwd: "{{vault_psdash_pwd}}"
psdash_host_address: "psdash.aptrust.org"

# Nagios
nagios_server: nagios.aptrust.org

# Icinga2
icinga_server: icinga.aptrust.org
icinga2_db: "{{vault_icinga2_db}}"
icinga2_db_user: "{{vault_icinga2_db_user}}"
icinga2_db_pass: "{{vault_icinga2_db_pwd}}"

icinga2_mysql_auth_user   : "{{vault_icinga2_mysql_auth_user}}"
icinga2_mysql_auth_pass   : "{{vault_icinga2_mysql_auth_pass}}"

icinga2_db_auth           : "{{vault_icinga2_db_auth}}"
icinga2_db_auth_user      : "{{vault_icinga2_db_auth_user}}"
icinga2_db_auth_pass      : "{{vault_icinga2_db_auth_pass}}"
