---

include_vars: vault.yml
# APP Env as language agnostic variable
APP_ENV: 'demo'
GO_ENV: 'demo'
RAILS_ENV: 'demo'

# SSH
sshd_allow_users: ["{{system_default_user}}",cd3ef,andrew.diamond,adiamond,kec6en]

# Fedora
fedora_db_user: "{{vault_fedora_user}}"
fedora_db_pwd: "{{vault_fedora_dev_pwd}}"
var_fedora_pid_namespace: 'aptrust'

ruby_version: 2.3.1

# Pharos
pharos_local_db: False
pharos_db_host: "{{ vault_pharos_demo_db_host}}"
pharos_db_user: "{{ vault_pharos_dev_db_user}}"
pharos_db_pwd: "{{ vault_pharos_dev_db_pwd}}"

pharos_devise_key: "{{ vault_pharos_dev_devise_key}}"
pharos_rails_key: "{{ vault_pharos_dev_rails_key}}"
pharos_url: "https://demo.aptrust.org"

pharos_aws_ses_user: "{{vault_pharos_demo_aws_ses_user}}"
pharos_aws_ses_pwd: "{{vault_pharos_demo_aws_ses_pwd}}"

pharos_nsq_base_url: "http://demo-services.aptrust.org:4151"
# Pharos System user for API access
pharos_system_user: "system@aptrust.org"
pharos_system_user_pwd: !vault |
   $ANSIBLE_VAULT;1.1;AES256
   61613031333162343831343038373233623064633539633836393366643233613431663764323465
   3561313364386164313939666330323232363635373636390a653631663739326633313163313532
   36616535376432656662393061613866623163363334373830333933366337666562316436656634
   6132633435313633330a616562346661666330383164393065383134363937313730303661613665
   3234
pharos_system_user_key: "{{vault_pharos_demo_api_pwd}}"
# AWS RDS
pharos_rds_instance_type: "db.t2.medium"
pharos_db_size: '16'
pharos_vpc_sec_group: "sg-18a4ac62"
pharos_rds_subnet: "demo"

# AWS EFS/DBS
# External Filesystems
use_efs: false
use_ebs: false
# EFS PROD
efs_mount_uri: "fs-97ff5bde.efs.us-east-1.amazonaws.com:/"

# AWS EBS Autoscale
# Starter disk volume in GB for LVM
vg_disk_size: 50
nsq_address: "demo-services.aptrust.org:4151"

# Exchange Go Services
pharos_api_user: "{{vault_pharos_demo_api_user}}"
pharos_api_key: "{{vault_pharos_demo_api_pwd}}"

apt_cronjobs:
  apt_bucket_reader:
    hour: "*"
    minute: "*/16"
    params: "-stats={{goapp_log_path}}/apt_bucket_reader_stats.json"
  apt_queue:
    hour: "*/1"
    minute: "30"
    params: "-stats={{goapp_log_path}}/apt_queue_stats.json"
  apt_queue_fixity:
    hour: "*"
    minute: "*/30"
    params: "-maxfiles=2500"

ex_tardirectory: "/mnt/lvm/apt/data"
ex_restoredirectory: "/mnt/lvm/apt/restore"
ex_logdirectory: "/mnt/lvm/apt/logs"
ex_replicationdirectory: "/mnt/lvm/apt/replication"
ex_maxfilesize: "5368709120"
ex_skipalreadyprocessed: "true"
ex_deleteonsuccess: "true"
ex_logtostderr: "false"
ex_usevolumeservice: "false"
ex_volumeserviceport: 8898
ex_loglevel: 4
ex_bucketreadercachehours: 24
ex_bagvalidationconfigfile: "config/aptrust_bag_validation_config.json"
ex_bagitversion: "0.97"
ex_bagitencoding: "UTF-8"

ex_pharosurl: "{{pharos_url}}"
ex_pharosapiversion: "v2"

ex_nsqdhttpaddress: "http://demo-services.aptrust.org:4151"
ex_nsqlookupd: "demo-services.aptrust.org:4161"

ex_aptrusts3region: "us-east-1"
ex_aptrustglacierregion: "us-west-2"

ex_preservationbucket: "aptrust.test.preservation"
ex_replicationbucket: "aptrust.test.preservation.oregon"

ex_customrestorebucket: "aptrust.restore.test"
ex_restoretotestbuckets: "true"
ex_maxdayssincefixitycheck: 90

ex_fetchworker: {
        networkconnections: "8",
        workers: "4",
        nsqtopic: "apt_fetch_topic",
        nsqchannel: "apt_fetch_channel",
        maxattempts: "3",
        maxinflight: "20",
        heartbeatinterval: "10s",
        readtimeout: "60s",
        writetimeout: "10s",
        messagetimeout: "180m"
    }

ex_storeworker: {
        networkconnections: 16,
        workers: 8,
        nsqtopic: "apt_store_topic",
        nsqchannel: "apt_store_channel",
        maxattempts: "3",
        maxinflight: "20",
        heartbeatinterval: "10s",
        readtimeout: "60s",
        writetimeout: "10s",
        messagetimeout: "180m"
    }

ex_recordworker: {
        networkconnections: "8",
        workers: "4",
        nsqtopic: "apt_record_topic",
        nsqchannel: "apt_record_channel",
        maxattempts: "3",
        maxinflight: "20",
        heartbeatinterval: "10s",
        readtimeout: "60s",
        writetimeout: "10s",
        messagetimeout: "180m"
    }

ex_replicationworker: {
        networkconnections: "4",
        workers: "8",
        nsqtopic: "apt_replication_topic",
        nsqchannel: "apt_replication_channel",
        maxattempts: "3",
        maxinflight: "20",
        heartbeatinterval: "10s",
        readtimeout: "60s",
        writetimeout: "10s",
        messagetimeout: "180m"
    }

ex_restoreworker: {
        networkconnections: "8",
        workers: "4",
        nsqtopic: "apt_restore_topic",
        nsqchannel: "apt_restore_channel",
        maxattempts: "3",
        maxinflight: "20",
        heartbeatinterval: "10s",
        readtimeout: "60s",
        writetimeout: "10s",
        messagetimeout: "180m"
    }

ex_filedeleteworker: {
        networkconnections: "12",
        workers: "4",
        nsqtopic: "apt_file_delete_topic",
        nsqchannel: "apt_file_delete_channel",
        maxattempts: "3",
        maxinflight: "20",
        heartbeatinterval: "10s",
        readtimeout: "60s",
        writetimeout: "10s",
        messagetimeout: "30m"
    }

ex_fixityworker: {
        networkconnections: "4",
        workers: "4",
        nsqtopic: "apt_fixity_topic",
        nsqchannel: "apt_fixity_channel",
        maxattempts: "3",
        maxinflight: "20",
        heartbeatinterval: "10s",
        readtimeout: "60s",
        writetimeout: "10s",
        messagetimeout: "180m"
    }

ex_receivingbuckets: [
        'aptrust.receiving.test.chd.virginia.edu',
        'aptrust.receiving.test.columbia.edu',
        'aptrust.receiving.test.georgetown.edu',
        'aptrust.receiving.test.indiana.edu',
        'aptrust.receiving.test.jhu.edu',
        'aptrust.receiving.test.miami.edu',
        'aptrust.receiving.test.ncsu.edu',
        'aptrust.receiving.test.nd.edu',
        'aptrust.receiving.test.psu.edu',
        'aptrust.receiving.test.syr.edu',
        'aptrust.receiving.test.test.edu',
        'aptrust.receiving.test.uc.edu',
        'aptrust.receiving.test.uconn.edu',
        'aptrust.receiving.test.umd.edu',
        'aptrust.receiving.test.umich.edu',
        'aptrust.receiving.test.unc.edu',
        'aptrust.receiving.test.virginia.edu',
        'aptrust.receiving.test.vt.edu',
        'aptrust.receiving.test.vwu.edu'
    ]

ex_dpn: {
        localnode: "aptrust",
        logdirectory: "/mnt/lvm/dpn/logs",
        stagingdirectory: "/mnt/lvm/dpn/staging",
        remotenodehomedirectory: "/home",
        loglevel: "4",
        logtostderr: "false",
        replicatetonumnodes: "2",
        dpnapiversion: "api-v2",
        dpnpreservationbucket: "aptrust.dpn.test",
        acceptinvalidsslcerts: "false",
        usesshwithrsync: "true",
        dpnglacierregion: "us-east-1",
# TODO: Is this relative or absolute to the go bin or go src directory?
#       We may want to move configs in the bin directory anyways. and only
#       update them if the repo has updated.
        bagvalidationconfigfile: "config/dpn_bag_validation_config.json",
    }

ex_dpn_restclient: {
  comment: "Settings for our local DPN REST API server. Load LocalAuthToken from environment!",
  localserviceurl: "https://dpn-demo2.aptrust.org/",
  localapiroot: "api-v2",
  localauthtoken: ""
}

ex_dpn_defaultmetadata: {
  comment: "Config settings for common DPN bagit metadata",
  bagitversion: "0.97",
  bagitencoding: "UTF-8",
  ingestnodename: "APTrust",
  ingestnodeaddress: "160 McCormick Rd., Charlottesville, VA 22904",
  ingestnodecontactname: "APTrust Administrator",
  ingestnodecontactemail: "help@aptrust.org"
}

# comment: "remote node admin tokens are ignored in this config.",
ex_dpn_remotenodeadmintokensfortesting: {
  chron: "",
  hathi: "",
  sdr:   "",
  tdr:   ""
}

# comment: set these in the environment, not here. export dpn_<node>_token.,
ex_dpn_remotenodetokens: {
  chron: "",
  hathi: "",
  sdr:   "",
  tdr:   ""
}

# comment: "remote node urls in demo come from node records in the local rest service.",
ex_dpn_remotenodeurls: {
  chron: "",
  hathi: "",
  sdr:   "",
  tdr:   ""
}

ex_dpn_dpnpackageworker: {
  networkconnections: "8",
  workers: "4",
  nsqtopic: "dpn_package_topic",
  nsqchannel: "dpn_package_channel",
  maxattempts: "3",
  maxinflight: "20",
  heartbeatinterval: "10s",
  readtimeout: "60s",
  writetimeout: "10s",
  messagetimeout: "180m"
}

ex_dpn_dpnvalidationworker: {
  networkconnections: "8",
  workers: "4",
  nsqtopic: "dpn_validation_topic",
  nsqchannel: "dpn_validation_channel",
  maxattempts: "3",
  maxinflight: "20",
  heartbeatinterval: "10s",
  readtimeout: "60s",
  writetimeout: "10s",
  messagetimeout: "180m"
}

ex_dpn_dpncopyworker: {
  networkconnections: "8",
  workers: "4",
  nsqtopic: "dpn_copy_topic",
  nsqchannel: "dpn_copy_channel",
  maxattempts: "3",
  maxinflight: "20",
  heartbeatinterval: "10s",
  readtimeout: "60s",
  writetimeout: "10s",
  messagetimeout: "180m"
}

ex_dpn_dpningeststoreworker: {
  networkconnections: "4",
  workers: "4",
  nsqtopic: "dpn_ingest_store_topic",
  nsqchannel: "dpn_ingest_store_channel",
  maxattempts: "3",
  maxinflight: "20",
  heartbeatinterval: "10s",
  readtimeout: "60s",
  writetimeout: "10s",
  messagetimeout: "180m"
}

ex_dpn_dpningestrecordworker: {
  networkconnections: "4",
  workers: "4",
  nsqtopic: "dpn_record_topic",
  nsqchannel: "dpn_record_channel",
  maxattempts: "3",
  maxinflight: "20",
  heartbeatinterval: "10s",
  readtimeout: "60s",
  writetimeout: "10s",
  messagetimeout: "180m"
}

ex_dpn_dpnreplicationstoreworker: {
  networkconnections: "4",
  workers: "4",
  nsqtopic: "dpn_replication_store_topic",
  nsqchannel: "dpn_replication_store_channel",
  maxattempts: "3",
  maxinflight: "20",
  heartbeatinterval: "10s",
  readtimeout: "60s",
  writetimeout: "10s",
  messagetimeout: "180m"
}

ex_dpn_dpnrestoreworker: {
  networkconnections: "4",
  workers: "4",
  nsqtopic: "dpn_restore_topic",
  nsqchannel: "dpn_restore_channel",
  maxattempts: "3",
  maxinflight: "20",
  heartbeatinterval: "10s",
  readtimeout: "60s",
  writetimeout: "10s",
  messagetimeout: "180m"
}

# NSQ services config
ex_nsq_mem_queue_size: "0"
ex_nsq_data_path: "{{ex_tardirectory}}"
ex_nsq_tcp_address: "0.0.0.0:4150"
ex_nsq_broadcast_address: "{{hostname_fqdn}}"
ex_nsq_nsqlookupd_tcp_addresses: "127.0.0.1:4160"
ex_nsq_msg_timeout: "360m0s"
ex_nsq_max_msg_timeout: "720m0s"
