# file: postgresql/tasks/main.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]


- name: apt install
  include: install.yml
  when: ansible_pkg_mgr == "apt"
  tags: [postgresql, postgresql-install]

- include: install_yum.yml
  when: ansible_pkg_mgr == "yum"
  tags: [postgresql, postgresql-install]

- include: extensions.yml
  tags: [postgresql, postgresql-extensions]

- name: Postgresql | configure
  include: configure.yml
  tags: [postgresql, postgresql-configure]

- name: Postgresql | configure users
  include: users.yml
  tags: [postgresql, postgresql-users]

- name: Postgresql | configure databases
  include: databases.yml
  tags: [postgresql, postgresql-databases]

- include: users_privileges.yml
  tags: [postgresql, postgresql-users]

- include: monit.yml
  when: monit_protection is defined and monit_protection == true
  tags: [postgresql, postgresql-monit]
