---

- name: nginx restart
  service: name=nginx state=restarted

- name: nginx update-rc.d
  shell: update-rc.d nginx defaults

- name: nginx reload
  service: name=nginx state=reloaded

- name: php5-fpm restart
  service: name=php5-fpm state=restarted

- name: php-fpm restart
  service: name=php7.0-fpm state=restarted
