# handlers file for postfix
---
- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: new aliases
  command: newaliases

- name: postmap sasl_passwd
  command: postmap /etc/postfix/sasl_passwd

- name: postmap generic
  command: postmap /etc/postfix/generic

- name: send test email
  tags: test_email
  command: echo "This is a test message. Ignore me."| mail -s "System {{ ansible_hostname }} has been successfully provisioned with email." ops@aptrust.org
