# handlers file for postfix
---

- name: new aliases
  command: newaliases

- name: postmap sasl_passwd
  command: postmap /etc/postfix/sasl_passwd

- name: postmap generic
  command: postmap /etc/postfix/generic

- name: test_email
  tags: test_email
  shell: "echo 'This is a test message. Ignore me.'| mail -s 'System {{ ansible_hostname }} has been successfully provisioned with email.' ops@aptrust.org"

- name: restart postfix
  service:
    name: postfix
    state: restarted

