---
  - name: Nginx | Check if nginx present
    command: test -x /usr/sbin/nginx
    when: ansible_os_family == "Debian"
    ignore_errors: yes
    changed_when: False
    register: nginx_present
    tags: nginx

  - name: Apache | Check if is present
    command: test -x /usr/sbin/apache2
    when: ansible_os_family == "Debian"
    ignore_errors: yes
    changed_when: False
    register: apache2_present
    tags: nginx

  - name: Apache | Uninstall Apache2
    become: yes
    apt: name=apache2 state=absent
    when: ansible_os_family == "Debian" and apache2_present

  - name: Passenger | Add GPG key to apt keyring
    apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7
    when: ansible_os_family == "Debian" and nginx_present|failed
    tags: passenger
    become: yes

  - name: Passenger | Install needed packages
    become: yes
    apt: state=present pkg="{{item}}"
    with_items:
     - apt-transport-https
     - ca-certificates
    when: ansible_os_family == "Debian" and nginx_present|failed
    tags: passenger

  - name: Passenger | Add Passenger repository
    become: yes
    apt_repository: repo="deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main" state=present
    when: ansible_os_family == "Debian" and nginx_present|failed
    tags: passenger

  - name: Ruby | Install Nginx extra and Phusion Passenger
    become: yes
    apt: state=present update_cache=yes pkg="{{item}}"
    when: ansible_os_family == "Debian" and nginx_present|failed
    with_items:
     - nginx-extras
     - passenger
    tags: passenger

  - name: Nginx | Create sites available/enabled directories
    file: path={{item}} state=directory mode=0755
    with_items:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
    when: ansible_os_family == "Debian" and nginx_present|failed
    tags:
      - nginx
      - passenger
    become: yes

  - name: Nginx | Configure include sites-enabled
    lineinfile: dest=/etc/nginx/nginx.conf regexp=".*sites-enabled.*" line="    include /etc/nginx/sites-enabled/*;" insertbefore="}" state=present
    tags:
      - nginx
      - passenger
    when: ansible_os_family == "Debian" and nginx_present|failed
    become: yes

  - name: Nginx | Disable default site
    file: path=/etc/nginx/sites-enabled/default state=absent
    tags:
      - nginx
      - passenger
# Note: nginx_present failed does not make sense as condition.
#    when: ansible_os_family == "Debian" and nginx_present|failed
    become: yes

  - name: Nginx | Copy nginx.conf template
    become: yes
    template: src="nginx.conf.j2" dest="/etc/nginx/nginx.conf" owner=root group=root mode=0644
    when: ansible_os_family == "Debian"
    notify: nginx reload
    tags:
      - nginx
      - passenger

  - name: Nginx | Set ruby to system one
    become: yes
    lineinfile: dest=/etc/nginx/passenger.conf regexp="^(\s*)#\s*passenger_ruby" line="passenger_ruby /usr/local/bin/ruby;" backrefs=yes
    when: ansible_os_family == "Debian" and nginx_present|failed
    tags:
      - nginx
      - passenger

  - name: Nginx | Set ruby to system one
    become: yes
    lineinfile: dest=/etc/nginx/passenger.conf regexp="^(\s*)#\s*passenger_root" line="passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;" backrefs=yes
    when: ansible_os_family == "Debian" and nginx_present|failed
    tags:
      - nginx
      - passenger
    notify: nginx reload

  - name: Verify Passenger install
    become: true
    shell: "/usr/bin/passenger-config validate-install"
    register: passenger_verification
    changed_when: "passenger_verification.rc == 1"
    tags: verifypassenger

  - include: vhost.yml
