- name: Add managed vhost config file (if any vhosts are configured).
  template:
        src: nginx_vhost.conf.j2
        dest: "{{ nginx_vhost_path }}/{{ item.vhost_server_name }}.conf"
        mode: 0644
  with_items: nginx_vhosts
  when: nginx_vhosts|length > 0
  notify: nginx reload

- name: Remove managed vhost config file (if no vhosts are configured).
  file:
    path: "{{ nginx_vhost_path }}/{{ vhost_server_name }}.conf"
    state: absent
  when: not nginx_vhosts
  notify: nginx reload
