inst_id: cd3ef
inst_id_suffix: edu
inst_name: "University of BeesomeA"
inst_member: cd3ef
inst_type: member
inst_users:
  - name: joe.schmo
    email: jo@joe.com
    phone: +5341234567
  - name: betty.sue
    email: betty@joe.com
    phone: +6341234567
  - name: christian.dahlhausen.cd3ef
    email: ricebob@joe.com
    phone: +74412345672
  - name: foo.bar
    email: foo@bar.com
    phone: +8341234567
inst_admin:
  - christian.dahlhausen.cd3ef

