-   hosts: all
    vars_files:
      - "group_vars/vault.yml"
    vars:
        playbook_name: 'oneoff'
        # Defined in all.yml and
        #        mount_dir: /mnt/efs/apt

        appname:
          - {name: nginx, logdir: /var/log/nginxcopy }
          - { name: unattended-upgrades, logdir: /var/log/unattended-upgradescopy }

            # - {name: pharos, logdir: /var/www/repo.aptrust.org/pharos/current/log }

    roles:
      #      - common
      - central_logs



    tasks:
