---
-   hosts: exchange-services
    vars_files:
        - "group_vars/vault.yml"

    environment: "{{go_env}}"
    vars:
        playbook_name: exchange

        # Golang
        golang_workspace_user: "{{system_default_user}}"

    roles:
      - {role: common, tags: common}
      - {role: futurice.supervisor, tags: supervisor}
      - {role: sansible.golang, tags: golang}
      - {role: retr0h.nsq, tags: nsq}
      - {role: aptrust.exchange, tags: exchange}
    tasks:

    - name: Slack to all
      slack:
        token: "{{slack_token}}"
        msg: "{{playbook_name}} deployment on {{ inventory_hostname }} completed"
        icon_emoji: ":dog:"
        channel: 'ops'
      tags: [pharos,slack]
