---
# Deploy on all exchange servers:
#  ansible-playbook exchange.yml -t deploy --diff
# Deploy on a specific exchange server:
#  ansible-playbook exchange.yml -t deploy --diff -l dpn-demo2
# Deploy a specific branch of exchange:
#  ansible-playbook exchange.yml -t deploy --diff -e ex_git_branch=<specific_branchname>
-   hosts: exchange-servers
    vars_files:
        - "group_vars/vault.yml"

    environment: "{{go_env}}"
    vars:
        playbook_name: exchange

        # Golang
        golang_workspace_user: "{{system_default_user}}"
        golang_tarball: go1.10.linux-amd64.tar.gz
        golang_tarball_checksum: b5a64335f1490277b585832d1f6c7f8c6c11206cba5cd3f771dcb87b98ad1a33

        # Supervisor
        supervisor_user: "{{system_default_user}}"
        supervisor_user_group: "{{system_default_group}}"
        supervisor_pid_path: "/tmp"

    roles:
      - {role: common, tags: common}
      - {role: futurice.supervisor, tags: supervisor}
      - {role: sansible.golang, tags: golang}
      - {role: retr0h.nsq, tags: nsq}
        #  - {role: franklinkim.docker-compose, tags: docker-compose, when: ex_docker==true}
        #  - {role: mongrelion.docker, tags: docker, when: ex_docker==true}}
      - {role: aptrust.exchange, tags: [exchange, deploy]}
    tasks:

    - name: Slack to all
      slack:
        token: "{{slack_token}}"
        msg: "{{playbook_name}} deployment on {{ inventory_hostname }} completed"
        icon_emoji: ":dog:"
        channel: 'ops'
      tags: [exchange,slack,deploy]
