---
-   hosts: local-vagrant
    vars_files:
        - "group_vars/all.yml"
        - "group_vars/vault.yml"
    vars:
        playbook_name: fluctus
    # SSL
        ssl_cert: "{{ var_ssl_cert }}"
        ssl_key: "{{ var_ssl_key }}"
        ssl_chain: "{{ var_ssl_chain }}"
        ssl_cert_path: "{{ var_ssl_cert_path }}"
        ssl_key_path: "{{ var_ssl_key_path }}"
        ssl_chain_path: "{{ var_ssl_chain_path }}"

    # APACHE
        apache_vhosts:
          - servername: "{{ ansible_fqdn }}"
            documentroot: "/var/www/{{ ansible_fqdn }}/{{ playbook_name }}"
            serveradmin: "ops@aptrust.org"
            extra_parameters: |
                # Redirect all http to https per default
                RewriteEngine On
                RewriteCond %{HTTPS} !=on
                RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
        apache_vhosts_ssl:
          - servername: "{{ ansible_fqdn }}"
            documentroot: "/var/www/{{ ansible_fqdn }}/{{ playbook_name }}"
            serveradmin: "ops@aptrust.org"
            certificate_file: "{{ var_ssl_cert_path }}"
            certificate_key_file: "{{ var_ssl_key_path }}"
            certificate_chain_file: "{{ var_ssl_chain_path }}"

        apache_mods_enabled:
            - rewrite.load
            - ssl.load
        apache_mods_disabled: []

    # AWS CREDENTIALS
    #AWS_ACCESS_KEY_ID: "{{ var_aws_access_key_id }}"
    #AWS_SECRET_ACCESS_KEY: "{{ var_aws_secret_access_key }}"

    # RUBY and RBENV
        rbenv:
          env: user
          version: v0.4.0
          ruby_version: 2.1.5
        rbenv_users: "{{ system_default_user }}"

    roles:
    #      - common
    #  - hostname
    #  - apache
    #  - ssl
    #  - postgresql
      - go

    tasks:
    - name: Create fluctus directory
      file: >
        state=directory
        path=/var/www/{{ ansible_fqdn }}/{{ playbook_name }}
        owner="{{system_default_user}}"
        mode=755
      become: yes

    - name: Install required packages
      apt: name="{{ item }}" state=present
      with_items:
        - postgresql-client
        - libpq-dev
        - nodejs
        - sqlite3
        - libsqlite3-dev

    - name: Checkout Fluctus repository
      git:
        repo=git://github.com/APTrust/fluctus
        dest="/var/www/{{ ansible_fqdn }}/{{ playbook_name }}"
        accept_hostkey=True


