---
  # Contact the monitored hosts to gather facts
- hosts: all
  gather_facts: True
  ignore_errors: yes

  # Contact the monitoring servers to copy host definitions
- hosts: monitoring_servers
  roles:
   - role: icinga2-ansible/icinga2-ansible-add-hosts
     configuration_logic: "object"
     host_attributes: |
       check_command = "http"
       vars.sla = "24x7"

     host_checks: |
       object Service "load_average" {
         host_name = "{{ hostvars[item].ansible_fqdn }}"
         check_command = "check_nrpe"
         vars.remote_nrpe_command = "check_load"
       }

       object Service "disk" {
         host_name = "{{ hostvars[item].ansible_fqdn }}"
         check_command = "check_nrpe"
         vars.remote_nrpe_command = "check_disk"
       }
     tags: add-hosts
