---
# Contact the monitored hosts to gather facts
- hosts: all
  gather_facts: True
  ignore_errors: yes

  # Contact the monitoring servers to copy host definitions
- hosts: monitoring_servers
  roles:
   - role: icinga2/icinga2-ansible-add-hosts
     configuration_logic: "object"
     host_attributes: |
       check_command = "hostalive"
       vars.sla = "24x7"

     host_checks: |
       object Service "load_average" {
         host_name = "{{ hostvars[inventory_hostname].ansible_fqdn }}"
         check_command = "load"
       }

       object Service "disk" {
         host_name = "{{ hostvars[inventory_hostname].ansible_fqdn }}"
         check_command = "disk"
       }
     tags: add-hosts
