---
-   hosts: all
    vars_files:
        - "group_vars/vault.yml"

    vars:
        playbook_name: nagios
        # NAGIOS
        nagios_nrpe_hosts: []

        nagios_users:
            - user: nagiosadmin
              pass: "{{nagiosadmin_pwd}}"
            - user: cd3ef
              pass: "{{cd3ef_pwd}}"
            - user: adiamond
              pass: "{{adiamond_pwd}}"

        admin_email: "{{ system_default_email }}"

        # NAGIOS-CONFIG
        nagios_hosts:
            - {name: 'apt-test-repository', address: 'test.aptrust.org', www: true, java_apps: true}
            - {name: 'apt-prod-repository', address: 'repository.aptrust.org', www: true, java_apps: true}

        nagios_host_groups:
          - name: 'www'
            alias: 'Web Servers'
            checks:
              - {command: 'check_nrpe!check_https', description: "Check https"}
              - {command: 'check_nrpe!check_users', description: "Check users"}
              - {command: 'check_nrpe!check_ssl_cert', description: "Check SSL certificate"}
          - name: 'java_apps'
            alias: 'Tomcat/Java Servers'

        nagios_commands:
#            - {name: "check_nrpe", command: 'check_nrpe -c $ARG1$ -H $HOSTADDRESS' }
            - {name: "check_https", command: 'check_http -w 5 -c 10 --ssl -H $HOSTADDRESS' }
            - {name: "check_ssl_cert", command: 'check_http -H $HOSTADDRESS -C 30,14'}
            - {name: 'check_http_npmjs_org', command: '$USER1$/check_http -H npmjs.org -I $HOSTADDRESS$ $ARG1$'}

     #APACHE
        apache_vhosts:
          - servername: "{{ ansible_fqdn }}"
            documentroot: "/var/www/{{ ansible_fqdn }}/{{ playbook_name }}"
            serveradmin: "ops@aptrust.org"
            extra_parameters: |
                # Redirect all http to https per default
                RewriteEngine On
                RewriteCond %{HTTPS} !=on
                RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

        apache_vhosts_ssl:
          - servername: "nagios.aptrust.org"
            documentroot: "/var/www/{{ ansible_fqdn }}/{{ playbook_name }}"
            serveradmin: "ops@aptrust.org"
            certificate_file: "{{ssl_cert_path}}"
            certificate_key_file: "{{ssl_key_path}}"
            certificate_chain_file: "{{ssl_interm_cert_path}}"
            extra_parameters: |
                # Redirect to /nagios
                RewriteEngine on
                RewriteRule   "^/$"  "/nagios/"  [R]


        apache_mods_enabled:
            - rewrite.load
            - socache_shmcb.load
            - ssl.load
            - ssl.conf

        apache_mods_disabled: []
        apache_remove_default_vhost: true

    roles:
#      - common
#      - hostname
#      - ssl
      #  - jdauphant.ssl-certs
#      - apache2
#      - nagios
      - nagios-config


    tasks:
    - name: Install required packages
      apt: name="{{ item }}" state=present
      with_items:
        - postgresql-client
        - libpq-dev
        - nodejs
        - sqlite3
        - libsqlite3-dev
