---
# This is used to ramp up a new institution and not require manual GUI interaction


# 1. Create S3 buckets
# 2. Create IAM Group
# 3. Create IAM Users
- name: Setting up AWS buckets and groups
  hosts: localhost
  connection: local
  gather_facts: False
  become: no

  vars:
    inst_id: cd3ef.test
    inst_type: subscriber
    inst_users:
      - david.bowie
      - tom.petty
      - bruce.springsteen

  tasks:
    - name: Create S3 buckets
      s3_bucket:
        name: "aptrust.{{ item }}.{{inst_id}}.edu"
        state: present
        tags:
          institution: "{{inst_id}}"
          institution_type: "{{inst_type}}"
          institution_member: "{{inst_member}}"
      with_items:
          - receiving
          - restore
          - receiving.test
          - restore.test
      register: new_buckets
      tags: new_buckets

    - name: Enable S3 logging
      s3_logging:
         name: "{{ item.name }}"
         target_bucket: aptrust.s3.logs
         target_prefix: "{{item.name}}"
         state: present
         region: us-east1
         validate_certs: no
      with_items:
        - "{{new_buckets.results}}"
      tags: new_buckets

    - name: Create IAM Group
      iam:
        iam_type: group
        name: "{{ item }}"
        state: present
      with_items:
        - "{{inst_id}}.edu.users"
        - "test.{{inst_id}}.edu.users"
      register: new_groups
      tags: iamgroups

    - debug: msg="{{item.group_name}}"
      with_items:
        -  "{{ new_groups.results }}"
      tags: iamgroups

    - name: Add users to created groups
      iam:
        iam_type: user
        name: "{{item.1}}"
        state: present
        groups: "{{ item.0.group_name }}"
      with_together:
        -  "{{ new_groups.results }}"
        -  "{{ inst_users }}"
      tags: iamgroups
