-   hosts: all
    vars_files:
      - "group_vars/vault.yml"
    vars:
        playbook_name: 'nfs'

        # NFS Client
        nfs_client_imports:
          #          - local: "{{nfs_mount_dir}}/logs"
          #   remote: "{{nfs_export_dir}}/logs"
          - local: "{{nfs_mount_dir}}/backups"
            remote: "{{nfs_export_dir}}/backups"

        # NFS Server:
        nfs_exports:
          - path: "{{nfs_export_dir}}/{{nfs_directories}}"
            export: "{{nfs_directories}}"
    roles:
        - {role: common, tags: common}
        - {role: cd3ef.nfs, tags: nfs}

    tasks:
      #    - name: simulate long running op, allow to run for 45 sec, fire and forget
      # command: /bin/sleep 150
      # async: 60
      # poll: 10

