-   hosts: all
    vars_files:
      - "group_vars/vault.yml"
    vars:
        playbook_name: 'nfs'
        # TODO: Move to all.yml
        # name is root, subdirs are subdirs
        nfs_directories:
          - name: "apt"
            subdirs:
              #- "data"
              #- "logs"
              #- "restore"
              #- "replication"
          - name: "dpn"
            subdirs:
              #  - "data"
              # - "logs"
              # - "restore"
              # - "replication"
              # - "staging"
          - name: "ops_data"
            subdirs:
              - influxdb
              - grafana
              - logs

        # NFS Client
        nfs_client_imports:
          - local: "{{nfs_mount_dir}}/{{orgtype}}"
            remote: "{{nfs_export_dir}}/{{orgtype}}"
        # NFS Server:
        nfs_exports:
          - path: "{{nfs_export_dir}}/{{nfs_directories}}"
            export: "{{nfs_directories}}"
    roles:
        - {role: common, tags: common}
        - {role: cd3ef.nfs, tags: nfs}

    tasks:
      #    - name: simulate long running op, allow to run for 45 sec, fire and forget
      # command: /bin/sleep 150
      # async: 60
      # poll: 10

