-   hosts: all
    vars_files:
      - "group_vars/vault.yml"
    vars:
        playbook_name: 'oneoff'
        #    roles:
      #      - AsianChris.npm


    tasks:
      #    - name: simulate long running op, allow to run for 45 sec, fire and forget
      # command: /bin/sleep 150
      # async: 60
      # poll: 10

     - name: Copy sslexception file
       copy:
         src: 80ssl-exception
         dest: /etc/apt/apt.conf.d
         owner: "{{system_default_user}}"
         group: "{{system_default_group}}"
         mode: 0664

     - name: Update apt-cache
       become: true
       apt:
         update_cache: yes
