-   hosts: all
    vars_files:
      - "group_vars/vault.yml"
    vars:
        playbook_name: 'oneoff'
    roles:
      - dpn-common


    tasks:
    - name: simulate long running op, allow to run for 45 sec, fire and forget
      command: /bin/sleep 150
      async: 60
      poll: 10
