---
-   hosts: pharos
    vars_files:
        - "group_vars/vault.yml"

    environment: "{{ruby_env}}"

    vars:
        playbook_name: pharos
        # TODO: This should be determined by the git repo name at deploy time
        ansistrano_deploy_to: "/var/www/{{ansible_fqdn}}/{{playbook_name}}"
        ansistrano_deploy_via: "git"
        ansistrano_git_repo: "git@github.com:APTrust/pharos.git"
        ansistrano_git_branch: "develop"
        ansistrano_git_private_key: "{{aptdeploy_sshkey_private}}"

        # NGINX Webserver
        nginx_vhosts:
          - listen: "80 default_server"
            server_name: "_;"
            extra_parameters: |
              return 301 https://$host$request_uri;
          - listen: "443 ssl"
            server_name: "{{ansible_fqdn}};"
            extra_parameters: |
              root "{{ ansistrano_deploy_to }}";
              passenger_enabled on;
              passenger_base_uri /;
              passenger_app_root "{{ ansistrano_deploy_to }}/current;"
              passenger_app_env "{{ RAILS_ENV }};"
              passenger_friendly_error_pages off;

              ssl    on;
              ssl_certificate    "{{ ssl_cert_path }};"
              ssl_certificate_key "{{ ssl_key_path }};"

        # Pharos Role
        pharos_app_root: "{{ ansistrano_deploy_to }}/current"

        # RBenv
        rbenv:
          env: user
          version: v1.0.0
          ruby_version: 2.3.1

# THESE ARE SUPPLIED PER GROUP/HOST-VARS
## Rewrite to use aws_ses_user everywhere. currently mapped to postfix_sasl_user
    # AWS CREDENTIALS
    #AWS_ACCESS_KEY_ID: "{{ var_aws_access_key_id }}"
    #AWS_SECRET_ACCESS_KEY: "{{ var_aws_secret_access_key }}"

    #AWS_SES_USER: ""
    #AWS_SES_PASSWORD: ""


    roles:
      - {role: common, tags: common}
      - {role: hostname, tags: common}
      - {role: ssl, tags: ssl}
#      Not sure why I use this instead of just the SSL role.
#      Disabled for testing.
#      - jdauphant.ssl-certs
 #     - apache2
      - {role: oracle-java8, tags: oracle-java8 }
      - {role: go, tags: go}
      - {role: zzet.rbenv, tags: rbenv}
      - {role: cd3ef.nginx-passenger, tags: [nginx, passenger, nginx-passenger]}
      - {role: carlosbuenosvinos.ansistrano-deploy, tags: deploy}
      - {role: pharos, tags: pharos}
    tasks:
    - name: Install required packages
      debug: msg="Good day sir"
