---
-   hosts: pharos
    vars_files:
        - "group_vars/vault.yml"

    environment: "{{ruby_env}}"

    vars:
        playbook_name: pharos
        # TODO: This should be determined by the git repo name at deploy time
        ansistrano_deploy_to: "/var/www/{{ansible_fqdn}}/{{playbook_name}}"
        ansistrano_deploy_via: "git"
        ansistrano_git_repo: "git@github.com:APTrust/pharos.git"
        ansistrano_git_branch: "develop"
        ansistrano_git_private_key: "{{aptdeploy_sshkey_private}}"
# TODO: Test shared paths and see if any more tasks have to be set for this to work.
#        ansistrano_shared_paths: ["{{ansistrano_deploy_to}}/config"]
        ansistrano_keep_releases: 3

        # Pharos Role
        pharos_app_root: "{{ ansistrano_deploy_to }}/current"
        pharos_environment: "{{ruby_env}}"

        # NGINX Webserver
        nginx_vhosts:
          - listen: "80 default_server"
            server_name: "_"
            return: 301 https://$host$request_uri
          - listen: "443 ssl"
            server_name: "{{ansible_fqdn}}"
            root: "{{ ansistrano_deploy_to }}/current/public"
            access_log: "{{ansible_fqdn}}_access.log"
            error_log: "{{ansible_fqdn}}_error.log"
            extra_parameters: |
                passenger_enabled on;
                passenger_base_uri /;
                passenger_app_root {{ ansistrano_deploy_to }}/current;
                passenger_app_env {{ RAILS_ENV }};
                passenger_friendly_error_pages off;

                ssl    on;
                ssl_certificate    {{ ssl_cert_path }};
                ssl_certificate_key {{ ssl_key_path }};


        # RBenv
        rbenv:
          env: user
          version: v1.0.0
          ruby_version: 2.3.1

# THESE ARE SUPPLIED PER GROUP/HOST-VARS
## Rewrite to use aws_ses_user everywhere. currently mapped to postfix_sasl_user
    # AWS CREDENTIALS
    #AWS_ACCESS_KEY_ID: "{{ var_aws_access_key_id }}"
    #AWS_SECRET_ACCESS_KEY: "{{ var_aws_secret_access_key }}"

    #AWS_SES_USER: ""
    #AWS_SES_PASSWORD: ""


    roles:
      - {role: common, tags: common}
      - {role: oracle-java8, tags: oracle-java8 }
      - {role: go, tags: go}
      - {role: zzet.rbenv, tags: rbenv}
      - {role: cd3ef.nginx-passenger, tags: [nginx, passenger, nginx-passenger]}
      - {role: carlosbuenosvinos.ansistrano-deploy, tags: deploy}
      - {role: pharos, tags: pharos}
    tasks:

    - name: Slack to all
      slack:
        token: "{{slack_token}}"
        msg: "{{playbook_name}} deployment on {{ inventory_hostname }} completed"
        icon_emoji: ":dog:"
        channel: 'ops'
      tags: [pharos,slack]
