---

- name: Create certificate directories
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{docker_ssl_path}}"
    - "{{client_ssl_path}}"

#TODO: replace with openssl_certificate calls when 2.4+ is available
- name: Create and sign CA key/cert
  shell: openssl genrsa -out "{{client_ssl_path}}"/ca-key.pem 2048

- name: Create CA cert
  shell: |
      openssl req -x509 -new -nodes -key "{{client_ssl_path}}/ca-key.pem" \
      -days 10000 -out "{{client_ssl_path}}/ca.pem" -subj '/CN=docker-CA'

- name: Copy CA cert to "{{docker_ssl_path}}"
  synchronize:
    src: "{{client_ssl_path}}/ca.pem
    dest: "{{docker_ssl_path}}"



