---

- set_fact:
    setup_script_checksum: "md5:{{ setup_script_md5_sum }}"
  when: setup_script_md5_sum is defined and setup_script_md5_sum

- name: Download docker setup script for desired version
  get_url:
    url: "{{ setup_script_url }}"
    dest: "/tmp/docker-setup.sh"
    checksum: "{{ setup_script_checksum|default(omit) }}"
    mode: 0755

# TODO: Make this into Ansible tasks instead.
# TODO: Use official docker repos not rancher.
- name: Execute docker setup script
  shell: "/tmp/docker-setup.sh"

# TODO: Make this into Ansible tasks instead.
- name: Copy TLS config script
  script: dockertls.sh
  when: docker_tls
  tags: docker_tls

- include_tasks: dockertls.yml
  when: docker_tls

