---

# --- OLD rancher script docker setup ---
#- set_fact:
#    setup_script_checksum: "md5:{{ setup_script_md5_sum }}"
#  when: setup_script_md5_sum is defined and setup_script_md5_sum

#- name: Download docker setup script for desired version
#  get_url:
#    url: "{{ setup_script_url }}"
#    dest: "/tmp/docker-setup.sh"
#    checksum: "{{ setup_script_checksum|default(omit) }}"
#    mode: 0755

#- name: Execute docker setup script
#  shell: "/tmp/docker-setup.sh"

- name: Add GPG Key
  apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu \
          {{ ansible_distribution_release }} \
          stable"
    state: present
    update_cache: yes

- name: Install Docker pre-requisites
  apt:
    state: latest
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Install docker daemon and stuff
  apt:
    state: present
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
