---

- set_fact:
    setup_script_checksum: "md5:{{ setup_script_md5_sum }}"
  when: setup_script_md5_sum is defined and setup_script_md5_sum

- name: Download docker setup script for desired version
  get_url:
    url: "{{ setup_script_url }}"
    dest: "/tmp/docker-setup.sh"
    checksum: "{{ setup_script_checksum|default(omit) }}"
    mode: 0755

# TODO: Make this into Ansible tasks instead.
# TODO: Use official docker repos not rancher.
- name: Execute docker setup script
  shell: "/tmp/docker-setup.sh"

# TODO: Make this into Ansible tasks instead.
- name: Copy TLS config script
  script: "create-docker-tls.sh {{ansible_hostname}}.aptrust.org"
  args:
    creates: "/home/{{system_default_user}}/.docker/ssl/ca.pem"
  become_user: "{{system_default_user}}"
  when: docker_tls
  tags: docker_tls

- name: Copy certs to /etc/docker/ssl
  synchronize:
    src: "/home/{{system_default_user}}/.docker/"
    dest: "/etc/docker/ssl"
  delegate_to: "{{ inventory_hostname }}"
  when: docker_tls
  tags: docker_tls

- name: Get local users homedir
  local_action: shell echo ~
  become: false
  changed_when: false
  register: homedir
  tags: docker_tls, homedir, filepull, localdir, profileupdate

- name: make sure local .docker directory exists
  file:
    dest: "{{homedir.stdout}}/.docker/ssl"
    state: directory
    mode: 0775
  delegate_to: 127.0.0.1
  become: false
  when: docker_tls
  tags: docker_tls,localdir

- name: Copy client certs to localhost
  synchronize:
    mode: pull
    src: "/home/{{system_default_user}}/.docker/"
    dest: "{{homedir.stdout}}/.docker/ssl/"
    checksum: yes
    times: yes
  when: docker_tls
  tags: docker_tls, filepull

- name: Ensure control host is using remote docker host
  blockinfile:
    path: "{{homedir.stdout}}/{{item}}"
    block: |
      export DOCKER_HOST=tcp://docker.aptrust.org:2376
      # Ignore for now so we don't get unknown ca authority error.
      #export DOCKER_TLS_VERIFY=1
      export DOCKER_CERT_PATH=~/.docker/ssl
  delegate_to: 127.0.0.1
  with_items:
    - .profile
    - .bash_profile
  become: false
  register: profile_update
  tags: docker_tls, profileupdate

- name: Source .profile if changed
  command: source "{{homedir.stdout}}/{{item}}"
  become: false
  delegate_to: 127.0.0.1
  with_items:
    - .profile
    - .bash_profile
  when: profile_update|changed
  tags: docker_tls, profileupdate

