---
dpnserver_app_root: "/var/www/{{ansible_fqdn}}/dpn-server"
RAILS_ENV: 'development'

dpnserver_db: "dpnserver_{{RAILS_ENV}}"

# pharos_db_user: "pharos_admin"
# pharos_db_pwd: "s3cr3tp455w0rd"

# pharos_devise_key: "c0044b2aec4c34f7ce7342ce3b4367e4cf6757c1f8187a8916737e3dce07859c23648098ea8e26c6f472731b3971c23a48d3e436ebafcc4fadb20c56910040ed"
# pharos_rails_key: "6ea6849fb203a813ff2bd09275fb57246cbbabe01af1e52507791c7b5251f7d2819c723da646545ca44048a5e777f3ab517417f020d660d9e7d35a19cb9333"
dpnserver_url: "https://dpn-demo.aptrust.org"

# AWS RDS
# Note: sec_group and subnet have to be setup prior deployment
dpnserver_db_name: "dpn_demo"
dpnserver_rds_instance_type: "db.t2.medium"
dpnserver_db_size: '16'
dpnserver_vpc_sec_group: "sg-18a4ac62"
dpnserver_rds_subnet: "dpn-demo"

# If true, postgresql is installed locally and used for pharos db
dpnserver_local_db: False

#  secret_key_base: 5cb31aea99c331715e728df714eca7e45e0b5ed32080dac987551e62af51e8f0a107a72d9e0b3aa2dd9b6f66a00e00da40049c9d8fbd9fb80c75beadf4346a4f
#  salt: some_salt # generate with rake secret
#  cipher_key: some_cipher_key
#  cipher_iv: some_cipher_iv
#  local_namespace: hathi
#  local_api_root: https://dpn.hathitrust.org
#  staging_dir: /dpn/staging
#  repo_dir: /dpn/repo
#  transfer_private_key: /home/dpnuser/.ssh/id-rsa_transfer
