---
# Allowed setting are: installed, latest
sshd_pkg_state: installed
sshd_port: 22
sshd_permit_root_login: 'without-password'
sshd_host_keys: [ /etc/ssh/ssh_host_rsa_key, /etc/ssh/ssh_host_dsa_key, /etc/ssh/ssh_host_ecdsa_key, /etc/ssh/ssh_host_ed25519_key ]
sshd_listen_addresses: []
sshd_password_authentication: 'no'
sshd_print_motd: 'no'
