#jinja2: lstrip_blocks: "True"
version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    volumes:
      - ./mongo_data:/data/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms{{graylog_es_xm}}m -Xmx{{graylog_es_xm}}m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: {{graylog_mem_limit}}m
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.5-1
    volumes:
      - ./graylog_data:/usr/share/graylog/data
{% for jarr in graylog_plugins %}
      - ./{{ jarr }}:/usr/share/graylog/plugin/{{ jarr }}
{% endfor %}
{% for jsons in graylog_content_packs %}
      - ./{{ jsons }}:/usr/share/graylog/data/contentpacks/{{ jsons }}
{% endfor %}

    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET={{graylog_root_password}}
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2={{graylog_root_password_sha2}}
      - GRAYLOG_WEB_ENDPOINT_URI={{graylog_web_endpoint_uri}}
      - GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true
      - GRAYLOG_CONTENT_PACKS_AUTO_LOAD=grok-patterns.json,rails_content_pack.json,nginx_content_pack.json,http_monitor_content_pack.json
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # RAILS GELF UDP
      - 12219:12219/udp
      # Nginx access log
      - 12301:12301/udp
      # Nginx error log
      - 12302:12302/udp
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
