---
nagios_nrpe_server_bind_address: 127.0.0.1
nagios_nrpe_server_port: 5666
nagios_nrpe_server_allowed_hosts: 127.0.0.1


nagios_plugins:
 - { command: "check_disk", path: "{{ nagios_nrpe_server_plugins_dir }}/check_apt", arguments: "$ARG1$" }
 - { command: "check_ntp_time", path: "{{ nagios_nrpe_server_plugins_dir }}/check_by_ssh", arguments: "$ARG1$" }
 - { command: "check_load", path: "{{ nagios_nrpe_server_plugins_dir }}/check_dig", arguments: "$ARG1$" }
 - { command: "check_disk", path: "{{ nagios_nrpe_server_plugins_dir }}/check_disk", arguments: "$ARG1$" }
 - { command: "check_disk_smb", path: "{{ nagios_nrpe_server_plugins_dir }}/check_disk_smb", arguments: "$ARG1$" }
 - { command: "check_dns", path: "{{ nagios_nrpe_server_plugins_dir }}/check_dns", arguments: "$ARG1$" }
 - { command: "check_dummy", path: "{{ nagios_nrpe_server_plugins_dir }}/check_dummy", arguments: "$ARG1$" }
 - { command: "check_file_age", path: "{{ nagios_nrpe_server_plugins_dir }}/check_file_age", arguments: "$ARG1$" }
 - { command: "check_flexlm", path: "{{ nagios_nrpe_server_plugins_dir }}/check_flexlm", arguments: "$ARG1$" }
 - { command: "check_fping", path: "{{ nagios_nrpe_server_plugins_dir }}/check_fping", arguments: "$ARG1$" }
 - { command: "check_ftp", path: "{{ nagios_nrpe_server_plugins_dir }}/check_ftp", arguments: "$ARG1$" }
 - { command: "check_ide_smart", path: "{{ nagios_nrpe_server_plugins_dir }}/check_ide_smart", arguments: "$ARG1$" }
 - { command: "check_ifoperstatus", path: "{{ nagios_nrpe_server_plugins_dir }}/check_ifoperstatus", arguments: "$ARG1$" }
 - { command: "check_ifstatus", path: "{{ nagios_nrpe_server_plugins_dir }}/check_ifstatus", arguments: "$ARG1$" }
 - { command: "check_imap", path: "{{ nagios_nrpe_server_plugins_dir }}/check_imap", arguments: "$ARG1$" }
 - { command: "check_load", path: "{{ nagios_nrpe_server_plugins_dir }}/check_load", arguments: "$ARG1$" }
 - { command: "check_log", path: "{{ nagios_nrpe_server_plugins_dir }}/check_log", arguments: "$ARG1$" }
 - { command: "check_nagios", path: "{{ nagios_nrpe_server_plugins_dir }}/check_nagios", arguments: "$ARG1$" }
 - { command: "check_pgsql", path: "{{ nagios_nrpe_server_plugins_dir }}/check_pgsql", arguments: "$ARG1$" }
 - { command: "check_ping", path: "{{ nagios_nrpe_server_plugins_dir }}/check_ping", arguments: "$ARG1$" }
 - { command: "check_procs", path: "{{ nagios_nrpe_server_plugins_dir }}/check_procs", arguments: "$ARG1$" }
 - { command: "check_ssh", path: "{{ nagios_nrpe_server_plugins_dir }}/check_ssh", arguments: "$ARG1$" }
 - { command: "check_uptime", path: "{{ nagios_nrpe_server_plugins_dir }}/check_uptime", arguments: "$ARG1$" }
 - { command: "check_users", path: "{{ nagios_nrpe_server_plugins_dir }}/check_users", arguments: "$ARG1$" }
 - { command: "check_http", path: "{{ nagios_nrpe_server_plugins_dir }}/check_http", arguments: "$ARG1$" }
