---
- name: Setup WikiEditor extension
  blockinfile: dest="{{mediawiki_path}}/LocalSettings.php"
              insertafter="wfLoadExtension\( \'WikiEditor\'\ )\;"
              content= |
                $wgDefaultUserOptions\['usebetatoolbar'\] = 1;
                $wgDefaultUserOptions\['usebetatoolbar-cgd'\] = 1;
                $wgDefaultUserOptions\['wikieditor-preview'\] = 1;
                $wgDefaultUserOptions\['wikieditor-publish'\] = 1;
              state=present
  tags: wikieditor
