---
# X - Add Graylog format json
# Add second lines of logs to ensure file and graylog logging.
#

#- name: Update nginx.conf to include graylog_json logging format
#  blockinfile:
#   dest: "/etc/nginx/nginx.conf"
#    content: |
#               log_format graylog2_json escape=json '{ "timestamp": "$time_iso8601", '
#                       '"remote_addr": "$remote_addr", '
#                       '"body_bytes_sent": $body_bytes_sent, '
#                       '"request_time": $request_time, '
#                       '"response_status": $status, '
#                       '"request": "$request", '
#                       '"request_method": "$request_method", '
#                       '"host": "$host",'
#                       '"upstream_cache_status": "$upstream_cache_status",'
#                       '"upstream_addr": "$upstream_addr",'
#                       '"http_x_forwarded_for": "$http_x_forwarded_for",'
#                       '"http_referrer": "$http_referer", '
#                       '"http_user_agent": "$http_user_agent" }';
#    backup: yes
#    insertbefore: "access_log "
#    validate: "nginx -T -c %s"

- name: Copy graylog_logformat config
  copy:
    src: graylog_nginx.conf
    dest: /etc/nginx/conf.d/graylog_nginx.conf
    owner: "{{system_default_user}}"
    group: "{{system_default_group}}"
    mode: 0644

- name: Get vhost config filenames
  find:
    paths: "/etc/nginx/sites-enabled"
    patterns: "*.conf"
  register: vhost_files
  tags: vhostls

- name: For vhost add log-to-graylog settings
  blockinfile:
    dest: "{{ item.path }}"
    content: |
      access_log syslog:server={{graylog_dns}}:12301 graylog2_json;
      error_log syslog:server={{graylog_dns}}:12302 error;
    insertafter: "error_log "
  with_items: "{{ vhost_files.files }}"

- name: Check that nginx vhost config is correct
  command: nginx -t
  become: true
  register: nginx_config_check

- name: Reload NGINX config
  service:
    name: nginx
    state: reloaded
  when: nginx_config_check

