---
#
# Rails setup.
#

# Install libraries required for building various gems
# that our Rails app uses. Be sure to update cache first,
# since the typical Vagrant Ubuntu VM ships with an out-
# of-date apt cache.
  - name: install required packages
    sudo: yes
    apt: pkg={{item}} state=present update_cache=yes
    with_items:
        - sqlite3
        - libssl-dev
        - bundler
        - postgresql-client
        - libpq5
        - libpqxx-dev
        - libsqlite3-dev
        - nodejs
        - zip
        - mailutils
    environment:
        DEBIAN_FRONTEND: noninteractive
    tags:
        - packages
        - rails dependencies

# Check to see if the Oracle JVM version 7 is already installed.
# Install it if it's not already there.

# TODO: Get rid of scripts and put logic in here.
  - name: check java version
    script: has_oracle_1.7.sh
    no_log: true
    register: good_java

# TODO: Get rid of scripts and put logic in here.
  - name: install oracle jvm
    script: install_oracle_jvm.sh
    sudo: yes
    no_log: true
    when: not good_java.stdout == 'Yes'
    tags: packages

# Checkout Fluctus
#  - name: Create fluctus directory
#    become: yes
#    file: >
#      state=directory
#      path=/var/www/{{ ansible_fqdn }}/fluctus
#      owner="{{system_default_user}}"
#      mode=755

#  - stat: path=/var/www/{{ ansible_fqdn }}/fluctus
#    register: fluctus

  - name: checkout fluctus repo
    become: yes
    become_user: "{{ system_default_user }}"
    git:
      repo=git@github.com:APTrust/fluctus.git
      dest=/var/www/{{ ansible_fqdn }}/fluctus
      version=0.3.1
#    when: not fluctus.stat.exists
    tags: fluctus

# Set the right ruby interpreter
  - name: set ruby interpreter to {{ ruby_version }}
    shell: chdir=/var/www/{{ ansible_fqdn }}/fluctus rbenv local {{ ruby_version }}
    tags: rbenv

# Install bundler in local rbenv
  - name: install bundler
    shell: chdir=/var/www/{{ ansible_fqdn }}/fluctus gem install bundler
    tags: rails

# Load gems into the local rbenv
  - name: install items in fluctus gemfile
    #    shell: . /home/{{ system_default_user}}/.profile && chdir=/var/www/{{ ansible_fqdn }}/fluctus bundle install
    command: chdir=/var/www/{{ ansible_fqdn }}/fluctus bundle install
    tags: rails

# Generate Rails keys if they don't already exist
# We don't do the usual lineinfile because we don't
# want to keep overwriting the keys.
  - name: check for rails secret key
    command: grep RAILS_SECRET_KEY /home/{{ system_default_user }}/.profile
    register: rails_key_present
    ignore_errors: yes

  - name: check for devise secret key
    command: grep DEVISE_SECRET_KEY ~/.profile
    register: devise_key_present
    ignore_errors: yes

  - name: generate rails secret key
    shell: chdir=/var/www/{{ ansible_fqdn }}/fluctus bundle exec rake secret
    register: rails_key
    when: rails_key_present|failed
    tags: rails

  - name: add rails key to bash_profile if necessary
    when: rails_key_present|failed
    lineinfile:
      dest=/home/{{system_default_user}}/.profile
      state=present
      line="export RAILS_SECRET_KEY='{{ rails_key.stdout }}'"

  - name: generate devise secret key
    shell: chdir=/var/www/{{ ansible_fqdn }}/fluctus bundle exec rake secret
    when: devise_key_present|failed
    register: devise_key
    tags: rails

  - name: add devise key to bash_profile if necessary
    when: devise_key_present|failed
    lineinfile:
      dest=/home/{{system_default_user}}/.profile
      state=present
      line="export DEVISE_SECRET_KEY='{{ devise_key.stdout }}'"

# Set up Jetty/Solr
  - stat: path=/var/www/{{ ansible_fqdn }}/fluctus/jetty/lib
    register: jetty

  - name: set up jetty/solr
    script: setup_jetty.sh
    when: not jetty.stat.exists
    environment:
      PATH: "{{ path }}"
    tags: rails

  - lineinfile:
      dest=/home/{{system_default_user}}/.profile
      state=present
      line='export FEDORA_USER=fedoraAdmin'
    tags: rails

  - lineinfile:
      dest=/home/{{system_default_user}}/.profile
      state=present
      line='export FEDORA_PASS=fedoraAdmin'
    tags: rails

  - lineinfile:
      dest=/home/{{system_default_user}}/.profile
      state=present
      line="export FEDORA_URL='http://127.0.0.1:8983/fedora'"
    tags: rails


# Bring the dev and test databases up to date.
# If the the test db is not up to date, you can't run spec tests.
  - name: migrate dev database
    script: rails_migrate_db.sh
    environment:
      PATH: "{{ path }}"
    tags: rails

  - name: migrate test database
    shell: . /home/{{ system_default_user}}/.profile chdir=/var/www/{{ ansible_fqdn }}/fluctus bundle exec rake db:migrate
    environment:
      PATH: "{{ path }}"
      RAILS_ENV: "test"
    tags: rails
