##
# Add DPN users to the system.
# Run the rsync playbook before this, so that rssh is installed.
#
- name: add common users
  user: name="{{ item }}" state=present shell='/usr/bin/rssh'
  tags: dpn-common
  with_items:
    - dpn.hathi
    - dpn.chron
    - dpn.sdr
    - dpn.tdr

- name: add common user public keys
  authorized_key: user={{ item.name }} key="{{ item.keyfile }}" state=present
  tags: dpn-common
  with_items:
    - { name: 'dpn.hathi', keyfile: '{{dpn_hathi_sshkey}}' }
    - { name: 'dpn.chron', keyfile: '{{dpn_chron_sshkey}}' }
    - { name: 'dpn.sdr', keyfile: '{{dpn_sdr_sshkey}}' }
    - { name: 'dpn.tdr', keyfile: '{{dpn_tdr_sshkey}}' }


# Add dpn-apt private key
- name: Install private ssh key
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: 0600
    owner: "{{system_default_user}}"
  with_items:
    - { content: "{{ dpn_apt_private_sshkey }}", dest: "{{ dpn_transfer_private_key }}" }
    - { content: "{{ dpn_apt_public_sshkey }}", dest: "{{ dpn_transfer_public_key }}" }

# Message of the day explaining server is under control of Ansible.
- name: MOTD
  become: yes
  template: src=motd.j2 dest=/etc/motd owner=root mode=0644
  tags: common

