---

# Check if GO is installed, if not fail. Alternatively include go role in meta.

# Install required packages
# Needed for supervisor?
- name: Install required packages
  become: yes
  apt: pkg="{{item}}" state=present update_cache=yes
  with_items:
      - python-pip
      - libmagic-dev
      - git
      - bzr
      - mercurial
      - curl
  environment:
     DEBIAN_FRONTEND: noninteractive

# Set AWS Credentials as ENV
# TODO: Consider using separate creds for staging and prod S3 access.

- name: Set AWS ACCESS Credentials
  no_log: true
  lineinfile: >
    dest="/home/{{system_default_user}}/.profile"
    state=present
    line="{{item}}"
    insertafter=EOF
  with_items:
    - "export AWS_ACCESS_KEY_ID={{aws_go_user}}"
    - "export AWS_SECRET_ACCESS_KEY={{aws_go_pwd}}"

# Checkout Exchange repo
# This may be done using ansistrano. Alternatively we can just update the current version and restart supervisor services first. Is rollback necessary? Probably.

