# Identify type of server, DPN or APTrust
- name: Is this an APT or DPN Server
  set_fact: orgtype="{% if 'dpn' in ansible_hostname%}dpn{%else%}apt{%endif%}"
  tags: [always]

- import_tasks: dpn.yml
  when: orgtype == 'dpn'

- import_tasks: docker.yml
  when: ex_docker == true

- import_tasks: baremetal.yml
  when: ex_docker == false
