---
# handlers file for nagios
- name: restart apache
  service: name={{ apache_service }} state=restarted

- name: reload nagios
  service: name=nagios state=reloaded

- name: restart nagios
  service: name=nagios state=restarted
