---
language: python
python: 2.7
become: yes

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip
  - sudo pip -q install ansible

script:

  # Test role
  - >
      ansible-playbook --connection local -i localhost, playbook.yml
      | grep -q '.*failed=0'
      || (echo 'Playbook failed' > /dev/stderr && exit 1)


