## INSTALL reference https://gist.githubusercontent.com/mrlesmithjr/1da992b648771b9afd50/raw/33a9e42c4148553fc73fefbf33b97b3d1ea35495/confg_lvm.yml
# lvm_vgroup: Volume group to be named after instance_vg
# lvm_lvname: Logical volume name
# lvm_vsize: Logical volume size
# lvm_filesystem: FS, ext4

- name: Install LVM packages
  apt: name=lvm2 state=latest

- name: Create new LVM volume group
  lvg: vg={{ lvm_vgroup }} pvs=/dev/xvdf state=present

- name: Create new LVM logical volume
  lvol: vg={{ lvm_vgroup }} lv={{ lvm_lvname }} size={{ lvm_lvsize }}
  # when: create and config_lvm

- name: Create new filesystem on new LVM logical volume
  filesystem: fstype={{ lvm_filesystem }} dev=/dev/{{ lvm_vgroup }}/{{ lvm_lvname }}
  register: fsstats
 # when: create and config_lvm

# TODO: Mount dest should be a variable.
- name: Mount EBS data drive
  mount:
    src: /dev/{{lvm_vgroup}}/{{lvm_lvname}}
    path: /mnt/ebs
    fstype: ext4
    state: mounted

