---
# Creates local postgres database
#

- name: Install postgresql
  apt:
    name: ['postgresql', 'postgresql-contrib', 'libpq-dev']
    update_cache: yes

- name: Startup PGSQL
  service: name=postgresql state=started

- name: PHAROS | Create Postgres Pharos DB user
  postgresql_user: name="{{pharos_db_user}}"
                   password="{{pharos_db_pwd}}"

- name: PHAROS | Create Postgres Pharos DB
  postgresql_db: name="pharos_{{RAILS_ENV}}"
                 encoding='UTF-8'
                 owner="{{pharos_db_user}}"
                 state=present


