---
  - name: Set DEMO source environemnt db parameter for dbdump
    set_fact:
       pharos_src_db_host: "{{vault_pharos_demo_db_host}}"
       pharos_src_db_pwd: "{{vault_pharos_demo_db_pwd}}"
       pharos_src_db_user: "{{vault_pharos_demo_db_user}}"
       pharos_src_db: pharos_demo
       pharos_two_factor_key: "{{vault_pharos_demo_two_factor_key}}"
