---
# Staging environment deployment
# Every new deploy for the staging environment should
# - Destroy running Docker containers if exists (DOES THIS ALREADY in docker.yml)
# - Destroy old Staging DB, if exists
# - Recreate Staging DB from latest demo/prod db backup (env should be passed in as variable but may default to demo)
# - Recreate/Deploy Pharos Docker containers.
#
  - name: Make sure Docker services are shutdown and volumes removed.
    command: sudo docker-compose down -v
    args:
       chdir: "{{docker_app_path}}"
    tags: dockserv

  - name: Start Postgres container with initdb
    command: sudo docker-compose up -d  db
    args:
       chdir: "{{docker_app_path}}"
    tags: dbdump

  - name: Docker pg_dump
    shell: sudo docker-compose run --rm -e PGPASSWORD={{vault_pharos_demo_db_pwd}} -v /data/pharos/pgdata:/pgdata db bash -c "pg_dump --verbose -h {{vault_pharos_demo_db_host}} -p 5432 -Fc -C -O -U {{vault_pharos_demo_db_user}} pharos_demo > /pgdata/pharos_demo.dump"
    become: true
    args:
       chdir: "{{docker_app_path}}"
       executable: /bin/bash
    tags: dbdump2

  - name: Create DB
    #command: sudo docker-compose exec db bash -lc "createdb -U postgres pharos_staging && createuser -U {{pharos_db_user}} -d -E "
    command: sudo docker-compose exec -u postgres db psql -c "{{item}}"
    with_items:
       - "CREATE DATABASE pharos_demo;"
    args:
       chdir: "{{docker_app_path}}"
    tags: dbdumprestore

  - name: Restore pharos_demo.dump to local psql db service
    command: sudo docker-compose exec db bash -lc "pg_restore --verbose --clean  --no-acl --no-owner -U postgres -C -d postgres /pgdata/pharos_demo.dump"
    args:
       chdir: "{{docker_app_path}}"
    tags: dbdumprestore

  - name: Create DB and User
    #command: sudo docker-compose exec db bash -lc "createdb -U postgres pharos_staging && createuser -U {{pharos_db_user}} -d -E "
    command: sudo docker-compose exec -u postgres db psql -c "{{item}}"
    with_items:
       - "CREATE USER {{pharos_db_user}} WITH PASSWORD '{{pharos_db_pwd}}' CREATEDB"
       - "ALTER DATABASE pharos_demo RENAME TO pharos_staging"
       - "GRANT ALL PRIVILEGES ON DATABASE pharos_staging to {{pharos_db_user}};"
       - "GRANT ALL PRIVILEGES ON SCHEMA public to {{pharos_db_user}};"
       - "ALTER DATABASE pharos_staging OWNER TO {{pharos_db_user}};"
       - "GRANT ALL ON ALL TABLES IN SCHEMA public TO {{pharos_db_user}};"
    args:
      chdir: "{{docker_app_path}}"
    tags: dbdumprestore


# Next should startup all services again.
  - name: Start docker containers from compose
    command: docker-compose up -d chdir="{{docker_app_path}}"
    tags: dockserv2


