---
# This are required steps to set up staging with a replica of
# the Pharos production database.
#
#
# It requires AWS credentials with sufficent rights to make a backup
#
# `Use latest prod snapshot, restore on new instance in demo vpc
# - Identify latest snapshot per AWS CLI call
# - Restore latest prod RDS snapshot to new instance
# - update env vars on staging before starting containers
#

- name: set instance identifier
  set_fact:
      instance_identifier: "{{vault_pharos_prod_db_host.split('.')[0]}}"
  tags: lsnap

- debug: msg="{{instance_identifier}}"
  tags: lsnap

- name: Get latest snapshot ARN
  shell: aws rds describe-db-snapshots --region=us-east-1 --db-instance-identifier={{instance_identifier}} --query="reverse(sort_by(DBSnapshots, &SnapshotCreateTime))[0]|DBSnapshotArn" --output text
  register: prod_latest_snapshot
  tags: lsnap

- debug: msg="{{prod_latest_snapshot.stdout}}"
  tags: lsnap

# Restore a Postgres db instance from a snapshot, wait for it to become available again, and
#  then modify it to add your security group. Also, display the new endpoint.
#  Note that the "publicly_accessible" option is allowed here just as it is in the AWS CLI
- name: Restore latest pharos_production snapshot to prod-staging
  # connection: local
  become: false
  rds:
      aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      command: restore
      snapshot: "{{prod_latest_snapshot.stdout}}"
      instance_name: pharos-production-staging
      instance_type: db.t3.medium
      region: us-east-1
      zone: us-east-1a
      subnet: demo
      publicly_accessible: no
      wait: yes
      wait_timeout: 600
      tags:
          Name: pharos-production-staging
  register: rds

- name: Update vpc_security_group for prod-staging instance
  connection: local
  become: false
  rds:
      command: modify
      instance_name: pharos-production-staging
      region: us-east-1
      vpc_security_groups: sg-18a4ac62
      backup_retention: 0
      aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

- name: Display new instance_endpoint"
  debug:
      msg: "The new db endpoint is {{ rds.instance.endpoint }}"

- name: Set PRODUCTION Source db environment parameters
  set_fact:
      pharos_db_host: "{{rds.instance.endpoint}}"
      pharos_db_user: "{{vault_pharos_prod_db_user}}"
      pharos_db_pwd: "{{vault_pharos_prod_db_pwd}}"
      pharos_two_factor_key: "{{vault_pharos_prod_two_factor_key}}"
