---
# Staging environment deployment
# Every new deploy for the staging environment should
# - Destroy running Docker containers if exists (DOES THIS ALREADY in docker.yml)
# - Destroy old Staging DB, if exists
# - Recreate Staging DB from latest demo/prod db backup (env should be passed in as variable but may default to demo)
# - Recreate/Deploy Pharos Docker containers.

  - name: Make sure Docker services are shutdown and volumes removed.
    command: sudo docker-compose -f "{{dockercomposefile| default('docker-compose.yml')}}" down  --remove-orphans -v
    args:
       chdir: "{{dockerapp_path}}"
    tags: dockserv

  - name: Start Postgres container with initdb
    command: sudo docker-compose up -d  db
    args:
       chdir: "{{dockerapp_path}}"
    tags: dbdump

  - debug: msg="source_env is {{source_env}}"
    tags: always

  - name: Set DEMO source environemnt db parameter for dbdump
    set_fact:
       pharos_src_db_host: "{{vault_pharos_demo_db_host}}"
       pharos_src_db_pwd: "{{vault_pharos_demo_db_pwd}}"
       pharos_src_db_user: "{{vault_pharos_demo_db_user}}"
       pharos_src_db: pharos_demo
       pharos_two_factor_key: "{{vault_pharos_demo_two_factor_key}}"
    when: source_env is search("demo")
    tags: always

  - include_tasks: staging-production.yml
    when: source_env is search("prod")
    tags: always

  - name: Docker pg_dump RDS database
    shell: sudo docker-compose exec db bash -lc "PGPASSWORD={{pharos_src_db_pwd}} pg_dump -h {{pharos_src_db_host}} -p 5432 -Fc -C -O -U {{pharos_src_db_user}} {{pharos_src_db}} > /{{pharos_src_db}}.dump"
    become: true
    args:
       chdir: "{{dockerapp_path}}"
       executable: /bin/bash
    when: source_env is search("demo")
    tags: dbdump2

  - name: Create pharos src db DB to connect to later
    shell: sudo docker-compose exec -u postgres db psql -c "{{item}}"
    with_items:
       - "DROP DATABASE IF EXISTS pharos_staging;"
       - "DROP DATABASE IF EXISTS {{pharos_src_db}};"
       - "CREATE DATABASE {{pharos_src_db}};"
    args:
       chdir: "{{dockerapp_path}}"
    when: source_env is search("demo")
    tags: dbdumprestore

  - name: Delete pharos-production-staging instance
    # connection: local
    become: false
    rds:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        command: delete
        region: us-east-1
        instance_name: pharos-production-staging
        wait: yes
        wait_timeout: 600
    register: rds_deletion
    when: source_env is search("demo")
    tags: delete_pharos_production_staging

  - name: Restore pharos_demo.dump to local psql container
    command: sudo docker-compose exec db bash -lc "sleep 2 && pg_restore --verbose --no-acl --no-owner -U postgres -d {{pharos_src_db}} /{{pharos_src_db}}.dump"
    args:
       chdir: "{{dockerapp_path}}"
    when: source_env is search("demo")
    tags: dbdumprestore

    # Defining user as superuser since finding and setting correct privileges
    # on schema and tables is a pain. Won't matter as much anyways since psql
    # will only have pharos staging db.
  - name: Create DB and User permissions
    command: sudo docker-compose exec -u postgres db psql -c "{{item}}"
    with_items:
       - "CREATE USER {{pharos_db_user}} WITH PASSWORD '{{pharos_db_pwd}}' SUPERUSER"
       - "ALTER DATABASE {{pharos_src_db}} RENAME TO pharos_staging"
       - "ALTER DATABASE pharos_staging OWNER TO {{pharos_db_user}};"
       # - "GRANT ALL PRIVILEGES ON DATABASE pharos_staging to {{pharos_db_user}};"
       # - "GRANT ALL PRIVILEGES ON SCHEMA public to {{pharos_db_user}};"
       # - "GRANT ALL PRIVILEGES ON SCHEMA public to public;"
       # - "GRANT ALL ON ALL TABLES IN SCHEMA public TO {{pharos_db_user}};"
       # - "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO {{pharos_db_user}};"
    args:
       chdir: "{{dockerapp_path}}"
    ignore_errors: True
    when: source_env is search("demo")
    tags: dbdump

  - name: Update .env according to source_env
    lineinfile:
       path: "{{dockerapp_path}}/.env"
       regexp: '^{{item.key}}'
       line: "{{item.key}}{{item.value}}"
    with_items:
      - {key: 'TWO_FACTOR_KEY=', value: "{{pharos_two_factor_key}}"}
      - {key: 'PHAROS_DB_HOST=', value: "{{pharos_db_host}}"}
      - {key: 'PHAROS_DB_USER=', value: "{{pharos_db_user}}"}
      - {key: 'PHAROS_DB_PWD=', value: "{{pharos_db_pwd}}"}

  - name: Update environment in db
    command: sudo docker-compose run --rm migration bin/rails db:environment:set
    args:
       chdir: "{{dockerapp_path}}"
    tags: dbdump


# Next should startup all services again.
#  - name: Start docker containers from compose
#    command: docker-compose up -d chdir="{{dockerapp_path}}"
#    tags: dockserv2
