---
ssl_certs_country: "US"
ssl_certs_locality: "Charlottesville"
ssl_certs_organization: "Academic Preservation Trust"
ssl_certs_state: "Virginia"
ssl_certs_common_name: "{{ansible_fqdn}}"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"

ssl_certs_patch: "/etc/ssl/{{ssl_certs_common_name}}"
ssl_certs_path_owner: "www-data"
ssl_certs_path_group: "www-data"
ssl_certs_privkey_path: "{{ssl_certs_patch}}/{{ssl_certs_common_name}}.key"
ssl_certs_cert_path: "{{ssl_certs_patch}}/{{ssl_certs_common_name}}.pem"
ssl_certs_csr_path: "{{ssl_certs_patch}}/{{ssl_certs_common_name}}.csr"

ssl_certs_local_privkey_path: '{{inventory_dir|default(playbook_dir)}}/files/ssl/{{ssl_certs_common_name}}.key'
ssl_certs_local_cert_path: '{{inventory_dir|default(playbook_dir)}}/files/ssl/{{ssl_certs_common_name}}.pem'

ssl_certs_generate_self_signed: true
ssl_certs_key_size: "4048"
