---
# tasks file for icinga2-ansible-no-ui

- include: icinga2_Debian_install.yml
  when: ansible_os_family == 'Debian' and ansible_distribution != 'Ubuntu'

- include: icinga2_Ubuntu_install.yml
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'

- include: icinga2_RedHat_install.yml
  when: ansible_os_family == 'RedHat'

- include: icinga2_Gentoo_install.yml
  when: ansible_os_family == 'Gentoo'

- include: icinga2_configure.yml
  tags:
   - icinga2_configure

- include: master.yml
  tags: icingamaster
  when: icinga2_master

- include: slack_notifications.yml
  when: icinga2_slack
  tags: icinga2_slack

- include: slack_notifications-git.yml
  # when: icinga2_slack_git
  tags: icinga2_slack
