---
# tasks file for icinga2-ansible-no-ui

- include: icinga2_Debian_install.yml
  when: ansible_os_family == 'Debian'

- include: icinga2_RedHat_install.yml
  when: ansible_os_family == 'RedHat'

- include: icinga2_configure.yml
  tags:
   - icinga2_configure

- name: Install additional Nagios plugins
  include: nagios_additional_plugins.yml
  tags: nagios-additional-plugins

- name: Add additional plugins
  copy: src="{{ item }}" dest="{{nagios_plugin_dir}}/{{ item }}" owner=nagios group=nagios mode=0755
  with_items:
    - check_aws_rds.py
    - check_reboot_required.sh
  tags: ['rdsplugin']

- name: Install boto library
  pip: name=boto state=present
  tags: ['rdsplugin']

- name: Set boto creds
  blockinfile:
    dest: "/etc/boto.cfg"
    create: yes
    owner: "{{system_default_user}}"
    group: "{{deploy_group}}"
    mode: 0660
    content: |
        [Credentials]
        # These are read-only credentials.
        aws_access_key_id = {{ aws_ro_user }}
        aws_secret_access_key = {{ aws_ro_pwd }}
  tags: ['rdsplugin']
