---

- name: Deploy reverse proxy configurations
  template:
    src: reverse_proxy.conf.j2
    dest: "{{ nginx_reverse_proxy_config_directory }}/{{ item.config_name }}.conf"
  with_items: "{{ nginx_reverse_proxy_proxies }}"
  notify:
    - nginx restart
  tags: reverse_proxy


#nginx_vhost_path: "/etc/nginx/sites-enabled"
