---
# Creates local postgres database
#
- name: DPN-SERVER | Create Postgres DPN DB user
  postgresql_user: name="{{dpnserver_db_user}}"
                   password="{{dpnserver_db_pwd}}"

- name: DPN-SERVER | Create Postgres DPN DB
  postgresql_db: name="{{dpnserver_db_name}}"
                 encoding='UTF-8'
                 owner="{{dpnserver_db_user}}"
                 state=present

- name: DPN-SERVER | Update DB hostname if local
  set_fact: dpnserver_db_hostname=localhost



