- name: software-properties-common installed
  apt:
    name: software-properties-common
    state: latest

- name: certbot ppa added
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: certbot installed
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - certbot
    - openssl

- name: certbot nginx installed
  apt:
    name: python-certbot-nginx
    state: latest
  when: certbot_nginx

- name: certbot Apache installed
  apt:
    name: python-certbot-apache
    state: latest
  when: certbot_apache
