- name: Check if nginx is installed
  stat: path=/etc/init.d/nginx
  register: certbot_nginx
  changed_when: False
  tags: nginxcheck

- set_fact: certbot_nginx="{{ certbot_nginx.stat.exists }}"
  tags: nginxcheck

- name: Check if apache is installed
  stat: path=/etc/init.d/apache2
  register: certbot_apache
  changed_when: False
  tags: apachecheck

- set_fact: certbot_apache="{{ certbot_apache.stat.exists }}"
  tags: apachecheck

- debug: msg=" n {{certbot_nginx}} a {{certbot_apache}}"

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: "Check whether port 443 is available to avoid that certbot fails and returns: 'Could not bind TCP port 443 because it is already in use by another process'"
  wait_for:
    port: 443
    state: stopped
    timeout: "{{ certbot_waitfor_port_seconds }}"
  when: certbot_standalone

- name: certs created
  command: certbot certonly --standalone -d {{ item }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --text
  args:
    creates: "{{ certbot_live_home }}/{{ item }}/fullchain.pem"
  when: (certbot_create_certs) and (certbot_standalone)
  with_items:
    - "{{ certbot_list_of_certs_to_create }}"

- name: certs for nginx created
  command: certbot --nginx -d {{ item }} -m {{ certbot_mail_address }} --agree-tos --noninteractive
  args:
    creates: "{{ certbot_live_home }}/{{ item }}/fullchain.pem"
  when: (certbot_create_certs) and (certbot_nginx)
  with_items:
    - "{{ certbot_list_of_certs_to_create }}"

- name: Set renew job standalone
  set_fact:
    certbot_renew_certs_job: /usr/bin/certbot renew
  when: certbot_standalone

- name: Set renew job nginx
  set_fact:
    certbot_renew_certs_job: /usr/bin/certbot renew --nginx
  when: certbot_nginx

- name: renew certs every month
  cron:
    name: renewCertbotCerts
    minute: "{{ certbot_renew_certs_minute }}"
    hour: "{{ certbot_renew_certs_hour }}"
    month: "{{ certbot_renew_certs_month }}"
    weekday: "{{ certbot_renew_certs_weekday }}"
    job: "{{ certbot_renew_certs_job }}"
  when: certbot_renew_certs
