---

solr_workspace: "{% if ansible_bios_version != 'VirtualBox' %}/mnt/aptrust{% else %}/srv{% endif %}"

solr_create_user: true
solr_user: solr

# solr_version: "4.10.4"
solr_version: "4.7.2"
solr_mirror: "http://archive.apache.org/dist"

solr_service_name: solr
# solr_install_path: /opt/solr
# This is bad practice and creates a dependency.
# TODO: Refactor. Maybe combine Solr/Tomcat roles.
solr_install_path: /var/lib/tomcat7/webapps
solr_home: "{{solr_workspace}}/solr/home"
solr_log_file_path: /var/log/solr.log

solr_host: "0.0.0.0"
solr_port: "8983"
solr_xms: "256M"
solr_xmx: "512M"

solr_cores: ['production','development','test','demo']
solr_default_core: 'development'
