---
# NOTE:
# Former home of repo was /home/ubuntu/go/src/github.com/APTrust/exchange,
# new home is /srv/docker/exchange
#

- name: Ensure dockerd is installed and running
  command: docker --version
  tags: checkdock

- name: Setup dockerapp directory structure
  file:
    path: "{{item}}"
    owner: "{{system_default_user}}"
    group: "{{system_default_user}}"
    mode: 0755
    state: directory
  with_items:
      - "{{docker_app_path}}"
      - "{{docker_data_path}}"
      - "{{docker_data_path}}/config"
      - "{{docker_data_path}}/log"
  tags: makedir

- name: Set commit-version fact to git hash
  set_fact: gitversion="{{git_version}}"
  when: git_version is defined
  tags: gitclone, gitversion

- name: Set commit-version fact to branch
  set_fact: gitversion="{{git_branch}}"
  when: git_version is undefined
  tags: gitclone, gitversion

- stat: path={{docker_app_path}}/.git
  register: gitrepo
  tags: gitclone, gitversion

- debug: var=gitversion
  tags: gitclone, gitversion

    # https://github.com/ansible/ansible/issues/19809
- name: Reset repo for Ansible bug
  command: git reset --hard
  args:
      chdir: "{{docker_app_path}}"
  when: gitrepo.stat.isdir is defined
  tags: gitclone

   #    Git version/branch logic:
   #    when git branch defined, use branch head
   #    when git branch is undefined, error
   #    when git branch and git version is defined, git clone, git checkout
   #    when git version defined but git branch undefined, error

# Note: We only clone the repository for .env and config/env.json and
# docker-compose.yml
- name: Clone exchange repo
  git:
    repo: "git@github.com:APTrust/exchange.git"
    dest: "{{ docker_app_path }}"
    accept_hostkey: yes
    clone: yes
    update: yes
    force: yes
    version: "{{ gitversion | default(master)}}"
  become_user: "{{system_default_user}}"
  become: true
  register: gitclone
  tags: buildgo, gitclone

# Note: Environment env vars (user profile) supersede .env
# https://docs.docker.com/compose/environment-variables/#the-env-file
- name: Update env vars in .env
  lineinfile:
    dest: "{{docker_app_path }}/.env"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'nsq_mem_queue_size=', line: 'nsq_mem_queue_size={{ex_nsq_mem_queue_size}}' }
    - { regexp: 'nsq_data_path=', line: 'nsq_data_path={{ex_nsq_data_path}}' }
    - { regexp: 'nsq_broadcast_address=', line: 'nsq_broadcast_address={{ex_nsq_broadcast_address}}' }
    - { regexp: 'nsq_msg_timeout=', line: 'nsq_msg_timeout={{ex_nsq_msg_timeout}}' }
    - { regexp: 'nsq_max_msg_timeout=', line: 'nsq_max_msg_timeout={{ex_nsq_max_msg_timeout}}' }
#    - { regexp: 'nsq_max_msg_size=', line: 'nsq_max_msg_size={{ex_nsq_max_msg_size}}' }
    - { regexp: 'nsq_tcp_address=', line: 'nsq_tcp_address={{ex_nsq_tcp_address}}' }
    - { regexp: "AWS_ACCESS_KEY", line: "AWS_ACCESS_KEY={{aws_go_user}}"}
    - { regexp: "AWS_SECRET_ACCESS_KEY", line: "AWS_SECRET_ACCESS_KEY={{aws_go_pwd}}"}
    - { regexp: "PHAROS_API_USER", line: "PHAROS_API_USER={{pharos_api_user}}"}
    - { regexp: "PHAROS_API_KEY", line: "PHAROS_API_KEY={{pharos_api_key}}"}
  tags: dotenv

- name: "Create elastic EBS volume directories (dockerapp)"
  become: yes
  file:
    path: "{{mount_dir}}/{{item.0}}/{{item.1}}"
    owner: "{{system_default_user}}"
    group: "{{deploy_group}}"
    mode: 0775
    recurse: true
    state: directory
    unsafe_writes: true
    follow: false
  with_nested:
    - ['exchange']
    - ['data', 'restore', 'replication']
  tags: exchange_ebs

# Note: This will be used going forward in containerized apps.
# mounted as volume into each container.
- name: Update Exchange config file
  become_user: "{{system_default_user}}"
  become: true
  template:
    src: exchange.json.j2
    #    dest: "{{docker_app_path}}/config/{{GO_ENV}}.json"
    dest: "{{docker_data_path}}/config/config.json"

- name: Add APTrust cronjobs
  cron:
    name: "{{ item.key }}"
    user: "{{system_default_user}}"
    minute: "{{item.value.minute | default('*')}}"
    hour: "{{item.value.hour | default('*')}}"
    day: "{{item.value.day | default('*')}}"
    month: "{{item.value.month | default('*')}}"
    job: "sudo run-one docker run --rm --env-file {{docker_app_path}}/.env \
     {{docker_registry_key}}exchange_{{item.key}}:{{exchange_release}}-{{exchange_branch}} \
          {{item.value.params | default('')}} >> {{docker_data_path}}/log/cron_{{item.key}}.log 2>&1"
    state: present
    disabled: "{{item.value.disabled | default('no')}}"
  with_dict: "{{ apt_cronjobs }}"
  tags: cronjobs


# Ensure docker container running state.
- name: Start docker containers from compose
  docker_service:
    project_src: "{{docker_app_path}}/"
    files: docker-compose.yml
    pull: true
  vars:
      ansible_python_interpreter: "/usr/bin/env python-docker"
  tags: dockserv
