---
- include: user.yml
  when: solr_create_user

- name: Set solr_filename for Solr 5.x.
  set_fact:
    "solr_filename=solr-{{ solr_version }}"
  when: "solr_version.split('.')[0] == '5'"
  tags: [solrnew, solr_dir]

- name: Set solr_filename for Solr 4.x.
  set_fact:
    "solr_filename=solr-{{ solr_version }}"
  when: "solr_version.split('.')[0] == '4'"
  tags: [solrnew, solr_dir]

- name: Download Solr.
  get_url:
    url: "{{ solr_mirror }}/lucene/solr/{{ solr_version }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: no
  tags: solrnew

- name: Set solr_dir
  set_fact: solr_dir="{{solr_workspace}}/{{solr_filename}}"
  tags: solr_dir

- name: Unarchive solr
  become: yes
#  become_user: "{{system_default_user}}"
  command: tar -xvf {{solr_workspace}}/{{ solr_filename}}.tgz chdir={{ solr_workspace }} creates={{solr_workspace}}/{{solr_filename}}
  tags: solrnew

- name: Copy Solr components into place
  shell: cp -rnv {{ item.src }} {{ item.dest }} creates={{ item.creates }}
  with_items:
    # Solr example configuration and war file
    - src: "{{ solr_dir }}/dist/{{solr_filename}}.war"
      dest: "{{ solr_install_path }}/solr.war"
      creates: "{{ solr_install_path }}/solr.war"

    # Solr log4j logging configuration
    - src: "{{ solr_dir }}/example/lib/ext/*"
      dest: "/usr/share/tomcat7/lib/"
      creates: "/usr/share/tomcat7/log4j-1.2.16.jar"

    # Solr log4j.properties
    - src: "{{ solr_dir }}/example/resources/log4j.properties"
      dest: "/usr/share/tomcat7/lib/"
      creates: "/usr/share/tomcat7/lib/log4j.properties"
  tags: solrnew

- name: Ensure log file is created and has proper permissions.
  file:
    path: "/var/log/solr.log"
    state: touch
    owner: "{{ solr_user }}"
    group: root
    mode: 0664
  changed_when: false

- include: solr-home.yml
# Init script is not needed when running under Tomcat.
# - include: init-script.yml
