---
# TODO: Check if solr.xml should be in there or not.
- name: Check if solr_home is already set up.
  stat: "path={{ solr_home }}/solr.xml"
  register: solr_example
  tags: solrcore

- name: Check if solr core directories exist.
  stat: "path={{ solr_home}}/{{item}}"
  with_items: solr_cores
  register: solr_core_dir
  tags: solrcore

- name: Ensure solr_home directory exists and has correct permissions.
  file:
    path: "{{ solr_home }}"
    recurse: yes
    state: directory
    owner: "tomcat7"
    group: "tomcat7"
    mode: 0755
  when: not solr_example.stat.exists

- name: Copy Solr example into solr_home.
  # shell: "cp -r {{ solr_install_path }}/example/solr/* {{ solr_home }}"
  shell: "cp -r {{ solr_workspace }}/{{ solr_filename}}/example/solr/* {{ solr_home }}"
  when: not solr_example.stat.exists

- name: Fix the example solrconfig.xml file.
  replace:
    dest: "{{ solr_home }}/collection1/conf/solrconfig.xml"
    regexp: ^.+solr\.install\.dir.+$
    replace: ""
  when: "not solr_example.stat.exists and solr_version.split('.')[0] == '4'"

- name: Copying solr.xml template
  template:
    src: solr.xml.j2
    dest: "{{solr_home}}/solr.xml"
    owner: "{{solr_user}}"
    group: "{{solr_user}}"
    mode: 0640

- name: Ensure Solr home files are owned by the solr_user.
  file:
    path: "{{ solr_home }}"
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    recurse: yes
  when: not solr_example.stat.exists
