---
# TODO: Check if solr.xml should be in there or not.
- name: Check if solr_home is already set up.
  stat: "path={{ solr_home }}/solr.xml"
  register: solr_example
  tags: solrcore

- name: Check if solr core directories exist.
  stat: "path={{ solr_home}}/{{item}}"
  with_items: solr_cores
  register: solr_core_dir
  tags: solrcore

- name: Ensure solr_home directory exists and has correct permissions.
  file:
    path: "{{ solr_home }}"
    recurse: yes
    state: directory
    owner: "tomcat7"
    group: "tomcat7"
    mode: 0755
  when: not solr_example.stat.exists
  tags: solrcore

- name: Create missing core dir.
  file:
    path: "{{ solr_home }}/{{item.item}}"
    recurse: yes
    state: directory
    owner: "tomcat7"
    group: "tomcat7"
    mode: 0755
  with_items: "{{solr_core_dir.results}}"
  when: "{{item.stat.exists}} == false"
  register: missing_solr_core_dirs
  tags: solrcore

- name: Copy Solr example into solr_home.
  shell: cp -rn "{{ solr_workspace }}/{{ solr_filename}}/example/solr/collection1/." "{{ solr_home }}/{{item.item}}"
  with_items: "{{solr_core_dir.results}}"
  when: "{{item.stat.exists}} == false"
  tags: solrcore

- name: Fix the conf.properties
  replace:
    dest: "{{ solr_home }}/{{item}}/core.properties"
    regexp: collection1
    replace: "{{ item }}"
  with_items: solr_cores

- name: tmp for debugging
  set_fact: solr_dir=/srv/solr-4.7.2
  tags: symlink

# TODO: research if this is actually necessary.
- name: Symlink Solr contrib and dist
  file:
    src: "{{solr_dir}}/{{item}}"
    dest: "{{solr_home}}/{{item}}"
    owner: tomcat7
    group: "{{solr_user}}"
    state: link
  with_items:
    - contrib
    - dist
  tags: symlink

# TODO: change relative paths of default solrconfig.xml
- name: Fix lib paths of default solrconfig.xml
  replace:
    dest: "{{ solr_home }}/{{item}}/conf/solrconfig.xml"
    regexp: '<lib dir="../../../'
    replace: '<lib dir="{{solr_home}}/'
  with_items: solr_cores
  tags: symlink

# Note: This creates a dependency and breaks reusability of the solr role.
- name: Symlink Solr schema to fluctus schema
  file:
    src: "{{fluctus_solrschema}}"
    dest: "{{solr_home}}/{{item}}/conf/schema.xml"
    owner: tomcat7
    group: "{{solr_user}}"
    state: link
    force: yes
  with_items: solr_cores
  when: fluctus_solrconfig and fluctus_solrschema
  tags: symlink

# Note: This creates a dependency and breaks reusability of the solr role.
# Note: force:yes will always result in a change. It is used to remove existing file and replace it with a symlink
- name: Symlink Solr solrconfig to fluctus solrconfig
  file:
    src: "{{fluctus_solrconfig}}"
    dest: "{{solr_home}}/{{item}}/conf/solrconfig.xml"
    owner: tomcat7
    group: "{{solr_user}}"
    state: link
    force: yes
  with_items: solr_cores
  register: symlinked_solr
# TODO: revisit this as it breaks once either var is not defined.
#  when: (fluctus_solrconfig is defined) and (fluctus_solrschema is defined)
  tags: symlink

# TODO: change relative paths of default solrconfig.xml
# Note: This is a duplicate of a fix lib task above but is necessary
# to ensure portability of solr role if used without fluctus.
- name: Temp workaround to fix lib paths of fluctus solrconfig.xml
  replace:
    dest: "{{ solr_home }}/{{item}}/conf/solrconfig.xml"
    regexp: '<lib dir="/mnt/aptrust/solr/solr-4.7.2/'
    replace: '<lib dir="{{solr_home}}/'
  with_items: solr_cores
  when: "{{symlinked_solr.changed}} == true"
  tags: symlink

# Note omitting solr.xml in fluctus repo as cores are defined in Ansible.
- name: Copying solr.xml template
  template:
    src: solr.xml.j2
    dest: "{{solr_home}}/solr.xml"
    owner: "tomcat7"
    group: "{{solr_user}}"
    mode: 0640
  tags: solrcore

- name: Copying solr-webapp.xml template
  template:
    src: solr-webapp.xml.j2
    dest: "/etc/tomcat7/Catalina/localhost/solr.xml"
    owner: "tomcat7"
    group: "tomcat7"
    mode: 0644
  notify: restart tomcat
  tags: solrcore

- name: Ensure Solr home files are owned by the tomcat7 user.
  file:
    path: "{{ solr_home }}"
    owner: "tomcat7"
    group: "tomcat7"
    recurse: yes
  tags: solrcore
