---
- name: Check if solr_home is already set up.
  stat: "path={{ solr_home }}/solr.xml"
  register: solr_example
  tags: solrcore

- name: Check if solr core directories exist.
  stat: "path={{ solr_home}}/{{item}}"
  with_items: solr_cores
  register: solr_core_dir
  tags: solrcore

- name: Ensure solr_home directory exists and has correct permissions.
  file:
    path: "{{ solr_home }}"
    recurse: yes
    state: directory
    owner: "tomcat7"
    group: "tomcat7"
    mode: 0755
  when: not solr_example.stat.exists
  tags: solrcore

- name: Copy solr.war to solr_home
  shell: >
    cp -rnv "{{solr_install_path}}/solr.war" "{{solr_home}}"
    creates="{{solr_home}}/solr.war"
  when: solr_example.stat.exists

- name: Create missing core dir.
  file:
    path: "{{ solr_home }}/{{item.item}}"
    recurse: yes
    state: directory
    owner: "tomcat7"
    group: "tomcat7"
    mode: 0755
  with_items: "{{solr_core_dir.results}}"
  when: "{{item.stat.exists}} == false"
  register: missing_solr_core_dirs
  tags: solrcore

- name: Copy Solr example into solr_home.
  shell: cp -rn "{{ solr_workspace }}/{{ solr_filename}}/example/solr/collection1/." "{{ solr_home }}/{{item.item}}"
  with_items: "{{solr_core_dir.results}}"
  when: "{{item.stat.exists}} == false"
  tags: solrcore

- name: Fix the conf.properties
  replace:
    dest: "{{ solr_home }}/{{item}}/core.properties"
    regexp: collection1
    replace: "{{ item }}"
  with_items: solr_cores

- name: Check symlinks for contrib and dist.
  stat: path="{{solr_home}}/{{item}}"
  with_items:
    - contrib
    - dist
  register: cdsymlink
  tags: [symb, symlink]

- debug: var=cdsymlink
  tags: symb

- name: Symlink Solr contrib and dist
  file:
    src: "{{solr_dir}}/{{item.item}}"
    dest: "{{solr_home}}/{{item.item}}"
    owner: tomcat7
    group: tomcat7
# TODO: Check if this is ok.
#    group: "{{solr_user}}"
    state: link
  with_items: cdsymlink.results
  when: not item.stat.exists
  tags: [symlink, symb]

- name: Symlink Solr contrib/analysis-extras
  file:
    src: "{{solr_dir}}/contrib/analysis-extras"
    dest: "{{solr_home}}/lib"
    owner: tomcat7
    group: tomcat7
# TODO: Check if this is ok.
#    group: "{{solr_user}}"
    state: link
  tags: [symlink, symb]

# TODO: change relative paths of default solrconfig.xml once
# all machines have been Ansible deployed.
- name: Fix lib paths of default solrconfig.xml
  replace:
    dest: "{{ solr_home }}/{{item}}/conf/solrconfig.xml"
    regexp: '<lib dir="../../../'
    replace: '<lib dir="{{solr_home}}"'
  with_items: solr_cores
  # when: not fluctus_solrconfig
  tags: symlink

# Note: omitting solr.xml in fluctus repo as cores are defined in Ansible.
- name: Copying solr.xml template
  template:
    src: solr.xml.j2
    dest: "{{solr_home}}/solr.xml"
    owner: "tomcat7"
    group: "{{solr_user}}"
    mode: 0640
  tags: solrcore

- name: Copying solr-webapp.xml template
  template:
    src: solr-webapp.xml.j2
    dest: "/etc/tomcat7/Catalina/localhost/solr.xml"
    owner: "tomcat7"
    group: "tomcat7"
    mode: 0644
  notify: restart tomcat
  tags: solrcore

- name: Ensure Solr home files are owned by the tomcat7 user.
  file:
    path: "{{ solr_home }}"
    owner: "tomcat7"
    group: "tomcat7"
    recurse: yes
  tags: solrcore
