---
# Create EBS volume
# Attach EBS volume to instance
# Create filessystem
#

- name: Gather facts from new server
  setup:
    filter: ansible_hostname

- name: Get EC2 instance facts
  ec2_metadata_facts:

- name: Create blockdevice
  ec2_vol:
    instance: "{{ansible_ec2_instance_id}}"
    region: "{{ansible_ec2_placement_region}}"
    name: "{{ ansible_hostname }}_data"
    volume_size: 5
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: blockdevice

- name: Create filesystem
  filesystem:
    fstype: ext4
    dev: "{{block_device_name}}"

- name: mount the persistent block device
  mount:
    path: "{{ mount_point }}"
    src: "{{ block_device_name }}"
    fstype: ext4
    state: mounted
