---
# tasks file for icinga2-ansible-no-ui

- include: icinga2_Debian_install.yml
  when: ansible_os_family == 'Debian'

- include: icinga2_RedHat_install.yml
  when: ansible_os_family == 'RedHat'

- include: icinga2_configure.yml
  tags:
   - icinga2_configure

- name: Install additional Nagios plugins
  include: nagios_additional_plugins.yml
  tags: nagios-additional-plugins

- name: Install RDS plugin
  copy: src=pmp-check-aws-rds.py dest="{{nagios_plugin_dir}}/check_aws_rds.py" owner=nagios group=nagios mode=0755
  tags: ['rdsplugin']
