---
##
# Message of the day explaining server is under control of Ansible.
#
- name: MOTD
  template: src=motd.j2 dest=/etc/motd owner=root mode=0644
  tags: common

##
# Adding common users to the system.
#
- name: add common users
  user: name="{{ item.name }}"
        password='{{ item.passwd }}'
        state=present
        groups='admin,adm'
        shell='/bin/bash'
  tags: common
  with_items:
#    PW hash file needs to be added. mkpasswd -m
#    - { name: 'andrew.diamond', passwd: "{{ lookup('file', 'creds/andrew.diamond') }}" }
    - { name: 'cd3ef', passwd: "{{ lookup('file', 'creds/cd3ef') }}" }

- name: add common user public keys
  authorized_key: user={{ item.name }} key="{{ lookup('file', item.keyfile) }}" state=present
  tags: common
  with_items:
#    - { name: 'andrew.diamond', keyfile: '~/.ansible/external/files/public_keys/diamond_pub' }
    - { name: 'cd3ef', keyfile: '~/.ansible/external/files/cdahlhausen/cdahlhausen.pub' }

# We might want to tighten this. Sudo pwd is helpful and more secure. 
# If ops/stage user ubuntu: could have restrictive settings.
- name: Modifiy admins so they need no sudo password
  tags: common
  lineinfile: dest=/etc/sudoers state=present regexp='^%admin ALL\=' line='%admin ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'


##
# Install base packages
#
- name: install base packages
  tags: packages
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - sudo
    - curl
    - wget
    - git-core
    - tig
    - tmux
    - htop
    - iotop
    - bmon
    - vim-tiny
    - emacs23-nox

##
# Sendmail aliases workaround
# This makes sure that root and ubuntu user emails
# are being sent to ops@aptrust.org
#
- name: Check if postfix is installed
  shell: dpkg-query -W 'postfix'
  ignore_errors: True
  register: is_postfix

- name: Aliasing email addresses
  tags: configuration
  copy: src='aliases' dest=/etc/aliases owner=root group=root mode=0644 backup=yes
  register: result_aliasing
  when: is_postfix|failed 

- name: Activate email aliases
  tags: configuration
  shell: newaliases
  when: result_aliasing|changed

##
# Add monitoring script for disk space usage.
# Workaround in lieu of monitoring application.
#

- name: Add diskcheck.py
  tags: configuration
  git: repo=https://github.com/cdahlhausen/ops_scripts.git
       dest=/srv/ops_scripts
       accept_hostkey=yes
       force=yes

- name: Add diskcheck cron job
  tags: common
  cron: name="Check disk space" minute="*/10" hour="*" job="/srv/ops_scripts/diskcheck.py"
