---
# Setup folders
- name: ANSISTRANO | Ensure deployment base path exists
  file:
    state: directory
    path: "{{ ansistrano_deploy_to }}"
    owner: "{{system_default_user}}"
    group: "{{deploy_group}}"

- name: ANSISTRANO | Set releases path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}"
  register: ansistrano_releases_path

- name: ANSISTRANO | Ensure releases folder exists
  file:
    state: directory
    path: "{{ ansistrano_releases_path.stdout }}"
    owner: "{{system_default_user}}"
    group: "{{deploy_group}}"

- name: ANSISTRANO | Set shared path
  command: echo "{{ ansistrano_deploy_to }}/shared"
  register: ansistrano_shared_path

- name: ANSISTRANO | Ensure shared elements folder exists
  file:
    state: directory
    path: "{{ ansistrano_shared_path.stdout }}"
    owner: "{{system_default_user}}"
    group: "{{deploy_group}}"

