##
- name: Ensure hostname set
  hostname: name={{ inventory_hostname }}
  when: inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^{{ ansible_default_ipv4.address }}.+$"
    line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"


- name: install base packages
  become: yes
  apt:
    name:
     - sudo
     - curl
     - mailutils
     - wget
     - build-essential
     - software-properties-common
     - git-core
     - tig
     - tmux
     - htop
     - iotop
     - bmon
     - vim-tiny
     - emacs-nox
     - unzip
     - tar
     - python-pip
     - postgresql-client
     - libpq-dev
     - nodejs
     - sqlite3
     - libsqlite3-dev
     - nfs-common
     - python3-pip
# https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
     - acl
     - ntp
     - jq
    state: latest
    update_cache: true
  tags: packages, packlist

- name: Ensure ntp deamon is running
  service: name=ntp state=started
  tags: ntp

- name: Install AWS CLI tools and Boto
  become: yes
  pip:
    name:
      - awscli
      - boto

# Note: DPN is no more so we may want to get rid of orgtype alltogether.
# Note: Will keep this around for now until roles are updated
- name: Set orgtype to APT
  set_fact: orgtype=apt
  tags: [always, mountdir]

- name: Create Deploy group
  become: true
  group: name=deploy state=present gid=1234

# Adding common users to the system.
- name: add common users
  become: yes
  user: name="{{ item.name }}"
        password="{{ item.pwd }}"
        state=present
        groups=admin,adm,deploy,www-data
        shell='/bin/bash'
  with_items:
    - { name: 'adiamond', pwd: "{{ adiamond_pwd }}" }
    - { name: 'cd3ef', pwd: "{{ cd3ef_pwd }}" }
    - { name: 'kec6en', pwd: "{{ kec6en_pwd }}" }
    - { name: "{{ system_default_user}}", pwd: "{{ aptdeploy_pwd }}" }
  tags: [createusers, addcommonusers]

- name: add common user public keys
  become: true
  authorized_key: user="{{item.name}}" key="{{item.pubkeyfile}}" state=present
  with_items:
## Keys can be stored encrypted as a variable in group_vars/vault.yml or directly imported from GitHub
#    - { name: 'andrew.diamond', keyfile: '~/.ansible/external/files/public_keys/diamond_pub' }
#    - { name: 'cd3ef', pubkeyfile: "{{ inventory_dir }}/group_vars/vault/users/cd3ef/cd3ef2.pub" }
#    - { name: 'cd3ef', pubkeyfile: "{{ var_cd3ef_sshkey }}" }
    - { name: "adiamond", pubkeyfile: "{{ adiamond_sshkey }}" }
    - { name: "cd3ef", pubkeyfile: "{{ cd3ef_sshkey }}" }
    - { name: "kec6en", pubkeyfile: "{{ kec6en_sshkey }}" }
    - { name: "{{system_default_user}}", pubkeyfile: "{{aptdeploy_sshkey}}" }
    - { name: "{{system_default_user}}", pubkeyfile: "{{ cd3ef_sshkey }}"  }
  tags: [common, pubkeys]

- name: add common user home settings
  copy: src=group_vars/users/{{item}} dest=/home/ owner={{item}} group={{item}}
  with_items:
    - adiamond
    - cd3ef

# Message of the day explaining server is under control of Ansible.
- name: MOTD
  become: true
  template: src=motd.j2 dest=/etc/motd owner=root mode=0644
  tags: ["common", "motd"]

- name: Adjust /srv permissions.
  become: yes
  file: path=/srv owner="{{system_default_user}}" group="{{deploy_group}}" mode=0775

## Making sure github.com is a known_host
- name: Ensure github.com is a known host
  become_user: "{{ system_default_user }}"
  lineinfile:
    dest: /home/{{ system_default_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

# We might want to tighten this. Sudo pwd is helpful and more secure.
# For ops/stage user ubuntu: could have restrictive settings.
- name: Modifiy admins so they need no sudo password
  become: true
  tags: common
  lineinfile: dest=/etc/sudoers state=present regexp='^%admin ALL\=' line='%admin ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
