---
- name: restart nsqd
  service: name=nsqd state=restarted enabled=yes

- name: restart nsqadmin
  service: name=nsqadmin state=restarted enabled=yes

- name: restart nsqlookupd
  service: name=nsqlookupd state=restarted enabled=yes
