---
# Identify type of server, DPN or APTrust. Default to apt.
- name: Is this an APT or DPN Server
  set_fact: orgtype="{% if 'dpn' in ansible_hostname%}dpn{%else%}apt{%endif%}"
  tags: [always, mountdir]

- name: Check if EFS mount exists
  command: "mountpoint {{mount_dir}}/{{orgtype}}"
  register: mount_stat
  changed_when: False

- name: If logs already symlinked, ignore the rest..
  stat: path="{{item.logdir}}"
  register: logssym
  with_items: "{{centrallogs}}"
  tags: symdeb


- include: symlink.yml
  with_items: "{{centrallogs}}"
  #  when: mount_stat.rc == 0 and (logssym.stat.islnk is defined and logssym.stat.islnk == false)
  when: mount_stat.rc == 0


  # NOTE: THIS DOES NOT WORK WIHT A DICT OF MULTIPLE LOGDIRS. THE CONDITIONAL DOESNT
  # EVAL EVERY ITEM IN THE RESULTS LIST. NEED TO ITERATE THROUGH THE LIST SOMEHOW OR RECREATE
  # A LIST OF ONLY NON SYMLINKED ITEMS.

