---
- name: Check if EFS mount exists
  command: "mountpoint {{mount_dir}}/{{orgtype}}"
  register: mount_stat
  changed_when: False

- include: symlink.yml
  with_items: "{{appname}}"
  when: mount_stat.rc == 0

