# defaults file for postfix
---
postfix_install:
  - postfix
  - mailutils
  - libsasl2-2
  - sasl2-bin
  - libsasl2-modules
postfix_hostname: "{{ ansible_fqdn }}"
postfix_mailname: "{{ ansible_fqdn }}"
postfix_aliases: []
postfix_relayhost: false
postfix_relayhost_port: 587
postfix_relaytls: false
postfix_sasl_user: "postmaster@{{ ansible_domain }}"
postfix_sasl_pwd: 'k8+haga4@#pR'
postfix_inet_interfaces: all

system_default_email: "root@{{ ansible_domain}}"
