---
goapp_name: exchange
goapp_bin_path: "{{ go_env.GOPATH }}/bin"
goapp_src_path: "{{ go_env.GOPATH }}/src/github.com/APTrust/{{goapp_name}}"
goapp_cfg_path: "{{ goapp_src_path }}/config"
#goapp_log_path: "/mnt/lvm/{{orgtype}}/logs"
goapp_log_path: "{{ex_logdirectory}}"

# Build Go binaries.
buildgo: true

# Mount_dir
# Usually uses external filesystems EBS, NFS
# Setting default here which will create subdirectories
# regardless if any external filesystem is mounted there or not
mount_dir: /mnt

#Git branch to deploy
ex_git_branch: master

# Flag to deploy docker-only environment
ex_docker: false

# Docker related settings
dockerapp_path: "/srv/docker/exchange"
dockerapp_repo_path: "/srv/docker/exchange/repo"
dockerapp_data_path: "/data/exchange"


# Used to determine which services to deploy on server.
# Demo server will have ingeste and restore, prod will
# have either on a different server
ex_services: all # values: all, ingest, restore

ex_apt_services:
  - apt_fetch
  - apt_file_delete
  - apt_fixity_check
  - apt_record
  - apt_restore
  - apt_store
  - apt_volume_service
  - apt_glacier_restore_init
  - apt_file_restore

ex_dpn_services:
  - dpn_copy
  - dpn_ingest_record
  - dpn_ingest_store
  - dpn_package
  - dpn_replication_store
  - dpn_validate
  #  Disabled cause, you know. Titanic and Icebergs.
  #  - dpn_fixity_checker
  - dpn_glacier_restore_init
  - dpn_s3_retriever

apt_cronjobs:
  apt_bucket_reader:
    hour: "*/1"
    minute: "*/2"
    params: "-stats={{goapp_log_path}}/apt_bucket_reader_stats.json"
  apt_queue:
    hour: "*/1"
    minute: "*/30"
    params: "-stats={{goapp_log_path}}/apt_queue_stats.json"
  apt_queue_fixity:
    hour: "*/1"
    minute: "*/30"
    params: "-maxfiles=2500"
# This only runs in prod. See group_vars/production
#  apt_spot_test_restore:
#   hour: "1"


ex_tardirectory: "~/tmp/data"
ex_restoredirectory: "~/tmp/apt/restore"
ex_logdirectory: "~/tmp/apt/logs"
ex_replicationdirectory: "~/tmp/apt/replicate"
ex_maxfilesize: "100000000"

ex_pharosurl: "localhost:3000"
ex_pharosapiversion: "v2"
ex_nsqdhttpaddress: "http://localhost:4151"
ex_nsqlookupd: "localhost:4161"

ex_aptrusts3region: "us-east-1"
ex_aptrustglacierregion: "us-west-2"

ex_preservationbucket: "aptrust.test.preservation"
ex_replicationbucket: "aptrust.test.preservation.oregon"
ex_dpnpreservationbucket: "aptrust.dpn.test"
ex_restoretotestbuckets: "true"
ex_remotenodehomedirectory: "/home"

ex_localserviceurl: "https://dpn-demo.aptrust.org/"
