---
goapp_name: exchange
goapp_bin_path: "{{ go_env.GOPATH }}/bin"
goapp_src_path: "{{ go_env.GOPATH }}/src/github.com/APTrust/{{goapp_name}}"
goapp_cfg_path: "{{ goapp_src_path }}/config"
goapp_log_path: "/mnt/efs/apt/logs"

# Used to determine which services to deploy on server.
# Demo server will have ingeste and restore, prod will
# have either on a different server
ex_services: all # values: all, ingest, restore

goapp_services:
    ingest:
    - apt_fetch
    - apt_record
    - apt_store
    - apt_volume_service
    - dpn_sync
#    - dpn_copy
    - nsq_service
    restore: []


ex_tardirectory: "~/tmp/data"
ex_restoredirectory: "~/tmp/apt/restore"
ex_logdirectory: "~/tmp/apt/logs"
ex_replicationdirectory: "~/tmp/apt/replicate"
ex_maxfilesize: "100000000"

ex_pharosurl: "localhost:3000"
ex_pharosapiversion: "v2"
ex_nsqdhttpaddress: "http://localhost:4151"
ex_nsqlookupd: "localhost:4161"

ex_aptrusts3region: "us-east-1"
ex_aptrustglacierregion: "us-west-2"

ex_preservationbucket: "aptrust.test.preservation"
ex_replicationbucket: "aptrust.test.preservation.oregon"
ex_dpnpreservationbucket: "aptrust.dpn.test"
ex_restoretotestbuckets: "true"
ex_remotenodehomedirectory: "/home"

ex_localserviceurl: "https://dpn-demo.aptrust.org/"
