- hosts: vm
  remote_user: vagrant
  become: true
  gather_facts: yes
  vars:
    user: vagrant
    home_directory: "/home/{{ user }}"
    deploy_to: "{{ home_directory }}"

    rails_env: development

    gem_home: "{{ home_directory }}/.gem"
    asset_precompile_diff_paths:
      - { current: "{{ current_path }}/app/assets", next: "{{ build_path }}/app/assets" }
      - { current: "{{ current_path }}/vendor/assets", next: "{{ build_path }}/vendor/assets" }

  roles:
    - install-ruby
    -
      role: nicolai86.prepare-release

      repo: https://github.com/nicolai86/pattern-manager.git
      branch: master

      symlinks:
        - { src: "{{ shared_path }}/config/database.yml", dest: "{{ build_path }}/config/database.yml" }
        - { src: "{{ shared_path }}/_db", dest: "{{ build_path }}/_db" }

      directories:
        - "{{ shared_path }}/config"
        - "{{ shared_path }}/_db"

      templates:
        - { src: "templates/database.j2", dest: "{{ shared_path }}/config/database.yml" }

    - setup-db

    -
      role: nicolai86.rails-deployment

      migrate: yes
      compile_assets: yes
      force_migrate: no
      force_asset_compilation: no

    - nicolai86.finalize-release
    - verify
