---

# This installs and deploys Pharos from github.com/APTrust/pharos
#
# Things to think about:
# - distinguish new deploy vs update deploy
# - distinguish local dev vs prod deploy
# -- USE RAILS_ENV as distinguished var
# - use bundler module
#
# X Use nginx vs Apache
#   - nginx
# X Use passenger as app server
#   - nginx-passenger installed.
# - Setup nginx vhost
# ## EBS only necessary for old architecture with fedora and solr.
# - Check for EBS mounts existence
#   -- add conditional to avoid when running virtualbox
# - Use AWS-CLI to mount correct EBS.
#   -- add conditional to avoid when running virtualbox
# - Consider rollback option a la capistrano (symlink checked out version)
# - Use deploy user for permissions
# - check for db migration necessity
# - cehck for asset compilation necessity
# - make delpoyed files owned by deploy group
#   -- should be achieved by using deploy user to check out app.

  - name: install required packages
    become: yes
    apt: pkg={{item}} state=present update_cache=yes
    with_items:
        - sqlite3
        - libssl-dev
        - bundler
        - postgresql-client
        - libpq5
        - libpqxx-dev
        - libsqlite3-dev
        - nodejs
        - zip
        - mailutils
    environment:
       DEBIAN_FRONTEND: noninteractive
    tags:
        - packages
        - rails dependencies

# Main playbook
# - name: Setup nginx virtual host
