---

# This installs and deploys Pharos from github.com/APTrust/pharos

  - name: install required packages
    become: yes
    apt: pkg={{item}} state=present update_cache=yes
    with_items:
        - sqlite3
        - libssl-dev
        - bundler
        - postgresql-client
        - libpq5
        - libpqxx-dev
        - libsqlite3-dev
        - nodejs
        - zip
        - mailutils
    environment:
       DEBIAN_FRONTEND: noninteractive
    tags:
        - packages
        - rails dependencies

# Set the right ruby interpreter
  - name: Set Ruby interpreters ruby_version
    shell: rbenv local "{{ruby_version}}"
    args:
      chdir: "{{pharos_app_root}}"
      creates: "{{pharos_app_root}}/.ruby-version"
    environment: "{{ruby_env}}"
    become: yes
    become_user: "{{ system_default_user }}"
    tags: rbenv_pharos

# Install Bundler
  - name: Install Bundler
    become: true
    become_user: "{{ system_default_user }}"
    gem:  name=bundler state=latest user_install=yes

# Install Gems from Gemfile
  - name: Install Pharos gems
    become: true
    become_user: "{{ system_default_user }}"
# Check if user_install would need to be set. User Vagrant doesn't run nginx or passenger, so not sure.
    bundler: state=present chdir="{{pharos_app_root}}"

# Create DB on RDS if it doesn't exist. AWS call to create. If Vagrant create DB locally.
  - name: Create DB on RDS
    rds:
        command: create
        instance_name: "pharos-{{RAILS_ENV}}"
        instance_type: "{{ pharos_rds_instance_type | default('db.t2.small') }}"
        size: "{{pharos_db_size | default('16') }}"
        username: "{{pharos_db_user}}"
        password: "{{pharos_db_pwd}}"
        db_name: "pharos_{{RAILS_ENV}}"
        db_engine: postgres
        region: "{{pharos_rds_region | default('us-east-1')}}"
# TODO: dependent on environment. set default to demo
# Note: security group name didn't work, only id. Security groups have to be configured manually via AWS web console at the moment.
        vpc_security_groups: "{{  pharos_vpc_sec_group | default('sg-65b4211f') }}"
        subnet: "{{ pharos_rds_subnet | default('demo') }}"
        wait_timeout: 600
        wait: yes
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        tags:
            Environment: "{{RAILS_ENV}}"
    tags: createrds
    register: rds_facts
    when: pharos_local_db == False

  - name: Set RDS db_host fact
    set_fact: pharos_db_host="{{rds_facts.instance.endpoint}}"
    when: pharos_local_db == False

  - name: Set local db_host fact
    set_fact: pharos_db_host="localhost"
    when: pharos_local_db == true

  - include: postgresql.yml
    when: ansible_bios_version == "VirtualBox" or pharos_local_db == true

# Note: This creates a dependency on ansistrano-deploy
  - name: Get Git Hash Fact
    shell: tail -n1 "{{pharos_app_root}}/REVISION" | cut -c1-5
    register: pharos_timestamp

  - name: Set Release fact
    set_fact: PHAROS_RELEASE="{{pharos_timestamp.stdout}}"

  - name: Define application environment configuration
    template:
        src: application.yml.j2
        dest: "{{pharos_app_root}}/config/application.yml"
        owner: "{{system_default_user}}"
        group: "{{deploy_group}}"
        mode: 0644

# Only loads DB schema at first deploy. Skipped when .schema_loaded exists
  - name: Load DB Schema at first deploy
    shell: "bundle exec rake db:schema:load RAILS_ENV={{RAILS_ENV}} && touch log/.schema_loaded"
    args:
        chdir: "{{pharos_app_root}}"
        creates: "{{pharos_app_root}}/log/.schema_loaded"
    become: true
    become_user: "{{ system_default_user }}"
    tags: dbmigrate

  - name: Migrate DB Schema
    shell: chdir="{{pharos_app_root}}" bundle exec rake db:migrate RAILS_ENV="{{RAILS_ENV}}"
    become: true
    become_user: "{{ system_default_user }}"
    tags: dbmigrate

# Creates institutions, roles and users
  - name: Initial Pharos setup
    shell: chdir="{{pharos_app_root}}" bundle exec rake pharos:setup
    become: true
    become_user: "{{ system_default_user }}"

  - name: Assets precompile
    shell: chdir="{{pharos_app_root}}" bundle exec rake assets:precompile
    become: true
    become_user: "{{ system_default_user }}"
    notify: reload nginx

# Note: This wipes the database first. But provides fixtures that pharos:setup does not.
  - name: PHAROS | Populate DB with fixtures
    shell: chdir="{{pharos_app_root}}" rake pharos:populate_db
    become: true
    become_user: "{{ system_default_user }}"
    when: RAILS_ENV == 'development'
    tags: populatedb
