---

# This installs and deploys Pharos from github.com/APTrust/pharos
#
# Things to think about:
# - distinguish new deploy vs update deploy
# - distinguish local dev vs prod deploy
# -- USE RAILS_ENV as distinguished var
# - use bundler module
#
# X Use nginx vs Apache
#   - nginx
# X Use passenger as app server
#   - nginx-passenger installed.
# - Setup nginx vhost
# ## EBS only necessary for old architecture with fedora and solr.
# - Check for EBS mounts existence
#   -- add conditional to avoid when running virtualbox
# - Use AWS-CLI to mount correct EBS.
#   -- add conditional to avoid when running virtualbox
# - Consider rollback option a la capistrano (symlink checked out version)
# - Use deploy user for permissions
# - check for db migration necessity
# - cehck for asset compilation necessity
# - make delpoyed files owned by deploy group
#   -- should be achieved by using deploy user to check out app.

  - name: install required packages
    become: yes
    apt: pkg={{item}} state=present update_cache=yes
    with_items:
        - sqlite3
        - libssl-dev
        - bundler
        - postgresql-client
        - libpq5
        - libpqxx-dev
        - libsqlite3-dev
        - nodejs
        - zip
        - mailutils
    environment:
       DEBIAN_FRONTEND: noninteractive
    tags:
        - packages
        - rails dependencies

#   NOT SURE IF NECESSARY.
#   - name: Change group ownership of fluctus to www-data
#    file: path="{{ fluctus_app_root }}" state=directory recurse=yes group=www-data

# Set the right ruby interpreter
  - name: Set Ruby interpreters ruby_version
    shell: rbenv local "{{ruby_version}}"
    args:
      chdir: "{{pharos_app_root}}"
      creates: "{{pharos_app_root}}/.ruby-version"
    environment: "{{ruby_env}}"
    become: yes
    become_user: "{{ system_default_user }}"
    tags: rbenv_pharos

# Install Bundler
  - name: Install Bundler
    become: true
    become_user: "{{ system_default_user }}"
    gem:  name=bundler state=latest user_install=yes

# Install Gems from Gemfile
  - name: Install Pharos gems
    become: true
    become_user: "{{ system_default_user }}"
# Check if user_install would need to be set. User Vagrant doesn't run nginx or passenger, so not sure.
    bundler: state=present chdir="{{pharos_app_root}}"

# Create DB on RDS if it doesn't exist. AWS call to create. If Vagrant create DB locally.
  - name: Create DB on RDS
    rds:
        command: create
        instance_name: "pharos-{{RAILS_ENV}}"
        instance_type: "{{ pharos_rds_instance_type | default('db.t2.small') }}"
        size: 16
        username: "{{pharos_db_user}}"
        password: "{{pharos_db_pwd}}"
        db_name: "pharos_{{RAILS_ENV}}"
        db_engine: postgres
        region: "{{pharos_rds_region | default('us-east-1')}}"
# TODO: dependent on environment. set default to demo
# Note: security group name didn't work, just id. Security groups have to be configured via AWS web console at the moment.
        vpc_security_groups: sg-65b4211f
        wait_timeout: 600
        wait: yes
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        tags:
            Environment: "{{RAILS_ENV}}"
    tags: createrds
    register: rds_facts
    when: pharos_local_db == False

  - name: Set RDS db_host fact
    set_fact: pharos_db_host="{{rds_facts.instance.endpoint}}"
    when: pharos_local_db == False

  - name: Set local db_host fact
    set_fact: pharos_db_host="localhost"
    when: pharos_local_db == true

  - include: postgresql.yml
    when: ansible_bios_version == "VirtualBox" or pharos_local_db == true

# Note: Temporary workaround for a revision. Should probably use the
# git ref hash to have something more intelligble
# git log --pretty=format:'%h' -n 1
# Note: This creates a dependency on ansistrano-deploy
  - name: Get Timestamp Fact
    shell: tail -n1 "{{pharos_app_root}}/REVISION" | cut -c1-5
    register: pharos_timestamp

  - name: Set Release fact
    set_fact: PHAROS_RELEASE="{{pharos_timestamp.stdout}}"

# TODO: set application.yml env configuration.
  - name: Define application environment configuration
    template:
        src: application.yml.j2
        dest: "{{pharos_app_root}}/config/application.yml"
        owner: "{{system_default_user}}"
        group: "{{deploy_group}}"
        mode: 0644

  - name: Migrate DB Schema
    command: chdir="{{pharos_app_root}}" RAILS_ENV="{{RAILS_ENV}}" bundle exec rake db:migrate
    become: true
    become_user: "{{ system_default_user }}"
    tags: dbmigrate

  - name: Initial Pharos setup
    shell: chdir="{{pharos_app_root}}" RAILS_ENV="{{RAILS_ENV}}" bundle exec rake pharos:setup
    become: true
    become_user: "{{ system_default_user }}"

  - name: Assets precompile
    shell: chdir="{{pharos_app_root}}" bundle exec rake assets:precompile
    become: true
    become_user: "{{ system_default_user }}"

# TODO: Create a handler instead and test for webserver type (apache vs nginx)
  - name: Restart Webserver
    service: name=nginx state=restarted

# Note: This wipes the database first. But provides fixtures that pharos:setup does not.
#  - name: PHAROS | Populate DB with fixtures
 #   shell: chdir="{{pharos_app_root}}" rake pharos:populate_db
 #   become: true
 #   become_user: "{{ system_default_user }}"
 #   when: "{{RAILS_ENV}} != production"
 #   tags: populatedb


# TODO: copy passenger wrapper into place

