---

# This installs and deploys Pharos from github.com/APTrust/pharos
#
# Things to think about:
# - distinguish new deploy vs update deploy
# - distinguish local dev vs prod deploy
# -- USE RAILS_ENV as distinguished var
# - use bundler module
#
# X Use nginx vs Apache
#   - nginx
# X Use passenger as app server
#   - nginx-passenger installed.
# - Setup nginx vhost
# ## EBS only necessary for old architecture with fedora and solr.
# - Check for EBS mounts existence
#   -- add conditional to avoid when running virtualbox
# - Use AWS-CLI to mount correct EBS.
#   -- add conditional to avoid when running virtualbox
# - Consider rollback option a la capistrano (symlink checked out version)
# - Use deploy user for permissions
# - check for db migration necessity
# - cehck for asset compilation necessity
# - make delpoyed files owned by deploy group
#   -- should be achieved by using deploy user to check out app.

  - name: install required packages
    become: yes
    apt: pkg={{item}} state=present update_cache=yes
    with_items:
        - sqlite3
        - libssl-dev
        - bundler
        - postgresql-client
        - libpq5
        - libpqxx-dev
        - libsqlite3-dev
        - nodejs
        - zip
        - mailutils
    environment:
       DEBIAN_FRONTEND: noninteractive
    tags:
        - packages
        - rails dependencies

# Main playbook
# - name: Setup nginx virtual host
#
# gem install bundler
# bundle install
# pharos:precompile_assets
# pharos:
#
#   NOT SURE IF NECESSARY.
#   - name: Change group ownership of fluctus to www-data
#    file: path="{{ fluctus_app_root }}" state=directory recurse=yes group=www-data

# Set the right ruby interpreter
  - name: set ruby interpreters ruby_version
    shell: rbenv local "{{ruby_version}}"
    args:
      chdir: "{{pharos_app_root}}"
      creates: "{{pharos_app_root}}/.ruby-version"
    become: yes
    become_user: "{{ system_default_user }}"
    tags: rbenv

# Install Bundler
  - name: Install Bundler
    become: true
    become_user: "{{ system_default_user }}"
#  command: bash -lc "gem install bundler"
    gem:  name=bundler state=latest user_install=yes

# Install Gems from Gemfile
  - name: Install Pharos gems
    become: true
    become_user: "{{ system_default_user }}"
# Check if user_install would need to be set. User Vagrant doesn't run nginx or passenger, so not sure.
    bundler: state=present chdir="{{pharos_app_root}}"

# Create DB on RDS if it doesn't exist. AWS call to create. If Vagrant create DB locally.
  - name: Create DB on RDS
    rds:
        command: create
        instance_name: "pharos-{{RAILS_ENV}}"
        instance_type: "{{ pharos_rds_instance_type | default(db.t2.small) }}"
        size: 16
        username: "{{pharos_db_user}}"
        password: "{{pharos_db_pwd}}"
        db_name: pharos
        db_engine: postgres
        region: "{{pharos_rds_region | default(us-east-1)}}"
# TODO: dependent on environment. set default to demo
# Note: security group name didn't work, just id. Security groups have to be configured via AWS web console at the moment.
        vpc_security_groups: sg-65b4211f
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        tags:
            Environment: "{{RAILS_ENV}}"
    tags: createrds
    register: rds_facts
# Note: Disabled during pharos deploy development.
#    when: {{ansible_bios_version != 'VirtualBox'}}

  - name: Set RDS db_host fact
    set_fact: pharos_db_host="{{rds_facts.instance.endpoint}}"
    when: postgres_local_db == False
    tags: createrds

  - name: Set local db_host fact
    set_fact: pharos_db_host="localhost"
    when: postgres_local_db == true
    tags: createrds

  - name: get me an instance endpoint
    debug: msg="{{rds_facts.instance.endpoint}}"
    tags: createrds

  - include: postgresql.yml
    when: ansible_bios_version == "VirtualBox" or postgres_local_db == true
    tags: pgsql

# TODO: rake db:migrate

# TODO: rake pharos:setup

# TODO: rake assets:precompile

# TODO: copy passenger wrapper into place
