---
- name: Ensure tomcat7 packages are installed (RedHat).
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - tomcat7
    - tomcat7-webapps
    - tomcat7-admin-webapps
  when: ansible_os_family == 'RedHat'

- name: Update apt cache (Debian).
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: Ensure tomcat7 is installed (Debian).
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - tomcat7
    - tomcat7-docs
    - tomcat7-admin
  when: ansible_os_family == 'Debian'

- name: Fix catalina.properties server loader directories
  replace:
    dest: /etc/tomcat7/catalina.properties
    regexp: ^(server\.loader\=)(\${catalina.home})(.*)(\${catalina.home})(.*)
    replace: '\1${catalina.base}\3${catalina.base}\5'
    backup: yes
  tags: tomcatreplace

- name: Fix catalina.properties shared loader directories
  replace:
    dest: /etc/tomcat7/catalina.properties
    regexp: ^(shared\.loader\=)(\${catalina.home})(.*)(\${catalina.home})(.*)
    replace: '\1${catalina.base}\3${catalina.base}\5'
    backup: yes
  tags: tomcatreplace

- name: Copy tomcat7 server.xml.
  template:
    src: server.xml.j2
    dest: /etc/tomcat7/server.xml
    owner: root
    group: tomcat7
    mode: 0644
  notify: restart tomcat

- name: Ensure tomcat7 is running.
  service:
    name: tomcat7
    state: started
    enabled: yes
  when: tomcat7_enabled
