---

# Install nfs packages
# Add exports into group vars
# -- ops_data/logs
# -- dpn
# -- apt
# Define exports
# Add ec2_security group module. Probably need to define vpc networks in group_vars
#

- name: Install nfs client packages
  apt:  name="{{item}}" state=latest
  with_items: "{{nfs_client_modules}}"

- name: Limit export to node
  delegate_to: "{{nfs_server_host}}"
  shell: touch /tmp/iwashere
  with_items: "{{ nfs_client_imports }}"
  tags: nfshostonly

- name: Touch the mountdir
  file:
    dest: "{{item}}"
    owner: "{{system_default_user}}"
    group: "{{system_default_user}}"
    state: directory
    mode: 0755
  with_items: "{{ nfs_mount_dir }}"

# Example: nfs_client_imports: [{ local: "/home", remote: "/home", remote: /home }] }
- name: mount the shared directories
  mount:
    name: "{{ item.local }}"
    boot: yes
    src: "{{ nfs_server_hostname}}:{{ item.remote }}"
    state: "{{ item.state | default('mounted') }}"
    fstype: nfs
    opts: "{{ item.opts | default('nfsvers=4.1,rsize=1048576,wsize=1048576,hard,intr,timeo=600,retrans=2') }}"
  with_items: "{{ nfs_client_imports }}"

