---

# Install nfs packages
# Add exports into group vars
# -- ops_data/logs
# -- dpn
# -- apt
# Define exports
# Add ec2_security group module. Probably need to define vpc networks in group_vars
#

- include: server.yml
  when: nfs_mode == 'server'

- include: client.yml
  when: nfs_mode == 'client'

- name: Ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes

