---
goapp_name: preserv
# Path for persisitent data between deploys.
# Note: These need to be on the host system, as they are mounted in the Docker
# containers.
goapp_data_path: "/data/{{goapp_name}}"
goapp_cfg_path: "{{ goapp_data_path }}/config"
goapp_log_path: "{{ goapp_data_path }}/logs"
preserv_data_path: "/mnt/lvm/preserv"

preserv_log_level: DEBUG

# Mount_dir
# Usually uses external filesystems EBS, NFS
# Setting default here which will create subdirectories
# regardless if any external filesystem is mounted there or not
mount_dir: /mnt/lvm

#Git branch to deploy
ex_git_version: master

# Docker related settings
docker_app_path: "/srv/docker/{{goapp_name}}"
docker_data_path: "{{goapp_data_path}}"
#docker_registry_key: registry.gitlab.com/aptrust/container-registry/
docker_registry_key: "aptrust/"

# Note: Paths below are in the Docker container, and are mounted to the host
# system.
preserv_cronjobs:
  ingest_bucket_reader:
    hour: "*/1"
    minute: "*/2"
    disabled: 'yes'
