#
# Make sure rsync and rssh are installed.
#

# Install rsync
  - name: rsync
    become: yes
    apt: pkg=rsync state=present

# Install rssh shell to limit what rsync users can do
  - name: rssh
    become: yes
    apt: pkg=rssh state=present
